import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 2:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]
        lesson["tense"]["rules"][1]["examples"] = data["grammar_negative"]
    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week4_data = {
    25: { # Restaurants
        "grammar_affirmative": [{"en": "I will order a pizza.", "vi": "Tôi sẽ gọi một chiếc pizza."}, {"en": "We will have dinner at 7.", "vi": "Chúng tôi sẽ ăn tối lúc 7 giờ."}, {"en": "The waiter will bring the bill.", "vi": "Người phục vụ sẽ mang hóa đơn đến."}],
        "grammar_negative": [{"en": "I won't eat spicy food.", "vi": "Tôi sẽ không ăn thức ăn cay."}, {"en": "She won't drink soda.", "vi": "Cô ấy sẽ không uống nước ngọt."}, {"en": "They won't tip the waiter.", "vi": "Họ sẽ không đưa tiền tip cho người phục vụ."}],
        "vocabulary": [
            {"word": "Restaurant", "phonetic": "/ˈres.tə.rɑːnt/", "meaning": "Nhà hàng", "example": "A nice restaurant.", "exampleVi": "Một nhà hàng đẹp."},
            {"word": "Menu", "phonetic": "/ˈmen.juː/", "meaning": "Thực đơn", "example": "Read the menu.", "exampleVi": "Đọc thực đơn."},
            {"word": "Order", "phonetic": "/ˈɔːr.dɚ/", "meaning": "Gọi món/Đặt hàng", "example": "Order food.", "exampleVi": "Gọi món ăn."},
            {"word": "Waiter", "phonetic": "/ˈweɪ.t̬ɚ/", "meaning": "Người phục vụ nam", "example": "Ask the waiter.", "exampleVi": "Hỏi người phục vụ."},
            {"word": "Waitress", "phonetic": "/ˈweɪ.trəs/", "meaning": "Người phục vụ nữ", "example": "She is a waitress.", "exampleVi": "Cô ấy là phục vụ nữ."},
            {"word": "Bill", "phonetic": "/bɪl/", "meaning": "Hóa đơn", "example": "Pay the bill.", "exampleVi": "Thanh toán hóa đơn."},
            {"word": "Delicious", "phonetic": "/dɪˈlɪʃ.əs/", "meaning": "Ngon", "example": "The food is delicious.", "exampleVi": "Thức ăn rất ngon."},
            {"word": "Table", "phonetic": "/ˈteɪ.bəl/", "meaning": "Cái bàn", "example": "Book a table.", "exampleVi": "Đặt bàn."},
            {"word": "Dessert", "phonetic": "/dɪˈzɝːt/", "meaning": "Món tráng miệng", "example": "I want dessert.", "exampleVi": "Tôi muốn món tráng miệng."},
            {"word": "Tip", "phonetic": "/tɪp/", "meaning": "Tiền tip/Tiền boa", "example": "Leave a tip.", "exampleVi": "Để lại tiền tip."}
        ],
        "listening": [{"en": "I will book a table for two at 8 PM.", "vi": "Tôi sẽ đặt bàn cho hai người lúc 8 giờ tối."}, {"en": "The waiter will bring the menu soon.", "vi": "Người phục vụ sẽ sớm mang thực đơn tới."}, {"en": "What will you order for dinner?", "vi": "Bạn sẽ gọi món gì cho bữa tối?"}, {"en": "I will try the delicious pasta.", "vi": "Tôi sẽ thử món mì Ý ngon tuyệt."}, {"en": "Will you have dessert after the meal?", "vi": "Bạn sẽ dùng món tráng miệng sau bữa ăn chứ?"}, {"en": "The bill won't be very expensive.", "vi": "Hóa đơn sẽ không quá đắt đâu."}, {"en": "She will pay by credit card.", "vi": "Cô ấy sẽ thanh toán bằng thẻ tín dụng."}, {"en": "We will leave a tip for the waitress.", "vi": "Chúng tôi sẽ để lại tiền tip cho cô phục vụ."}, {"en": "I won't drink wine today.", "vi": "Hôm nay tôi sẽ không uống rượu."}, {"en": "The food will be ready in ten minutes.", "vi": "Thức ăn sẽ sẵn sàng trong mười phút nữa."}],
        "speaking": [{"en": "Let's go to a restaurant.", "vi": "Chúng ta hãy đi nhà hàng đi."}, {"en": "Good idea, I'm hungry.", "vi": "Ý kiến hay đấy, tôi đang đói."}, {"en": "Can we see the menu?", "vi": "Chúng tôi có thể xem thực đơn không?"}, {"en": "Here it is.", "vi": "Đây ạ."}, {"en": "I'll order a steak.", "vi": "Tôi sẽ gọi món bít tết."}, {"en": "I'll have a salad.", "vi": "Tôi sẽ dùng món salad."}, {"en": "The food is delicious!", "vi": "Thức ăn ngon quá!"}, {"en": "Would you like dessert?", "vi": "Bạn có muốn dùng món tráng miệng không?"}, {"en": "No, just the bill, please.", "vi": "Không, cho tôi hóa đơn thôi."}, {"en": "I'll pay for it.", "vi": "Tôi sẽ trả tiền."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will _____ a pizza.", "answer": "order", "hint": "gọi món"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Ask the _____.", "answer": "waiter", "hint": "người phục vụ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Pay the _____.", "answer": "bill", "hint": "hóa đơn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The food is _____.", "answer": "delicious", "hint": "ngon"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Read the _____.", "answer": "menu", "hint": "thực đơn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Book a _____.", "answer": "table", "hint": "cái bàn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I want _____.", "answer": "dessert", "hint": "món tráng miệng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Leave a _____.", "answer": "tip", "hint": "tiền boa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A nice _____.", "answer": "restaurant", "hint": "nhà hàng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She is a _____.", "answer": "waitress", "hint": "phục vụ nữ"}],
        "quizzes": [{"question": "'Delicious' nghĩa là gì?", "options": ["Ngon", "Dở", "Mặn", "Ngọt"], "correct": 0}, {"question": "I _____ order some food.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "They _____ not tip him.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "Will you _____ a table?", "options": ["book", "books", "booking", "booked"], "correct": 0}, {"question": "The bill _____ be $50.", "options": ["will", "is", "are", "do"], "correct": 0}, {"question": "'Menu' nghĩa là gì?", "options": ["Thực đơn", "Hóa đơn", "Bàn ăn", "Món ăn"], "correct": 0}, {"question": "A _____ waitress.", "options": ["kind", "kindly", "kinds", "kinded"], "correct": 0}, {"question": "I'll _____ by card.", "options": ["pay", "pays", "paying", "paid"], "correct": 0}, {"question": "Would you like _____?", "options": ["dessert", "bill", "menu", "table"], "correct": 0}, {"question": "The food _____ be ready.", "options": ["will", "be", "is", "do"], "correct": 0}]
    },
    26: { # Social Media
        "grammar_affirmative": [{"en": "I will post a new photo.", "vi": "Tôi sẽ đăng một bức ảnh mới."}, {"en": "She will send you a link.", "vi": "Cô ấy sẽ gửi cho bạn một đường liên kết."}, {"en": "They will share the video.", "vi": "Họ sẽ chia sẻ video đó."}],
        "grammar_negative": [{"en": "I won't delete my account.", "vi": "Tôi sẽ không xóa tài khoản của mình."}, {"en": "He won't check his messages.", "vi": "Anh ấy sẽ không kiểm tra tin nhắn."}, {"en": "We won't use Facebook today.", "vi": "Chúng tôi sẽ không dùng Facebook hôm nay."}],
        "vocabulary": [
            {"word": "Social media", "phonetic": "/ˌsoʊ.ʃəl ˈmiː.di.ə/", "meaning": "Mạng xã hội", "example": "I use social media.", "exampleVi": "Tôi dùng mạng xã hội."},
            {"word": "Account", "phonetic": "/əˈkaʊnt/", "meaning": "Tài khoản", "example": "My Facebook account.", "exampleVi": "Tài khoản Facebook của tôi."},
            {"word": "Post", "phonetic": "/poʊst/", "meaning": "Đăng bài/Bài đăng", "example": "Post a picture.", "exampleVi": "Đăng một bức ảnh."},
            {"word": "Message", "phonetic": "/ˈmes.ɪdʒ/", "meaning": "Tin nhắn", "example": "Send a message.", "exampleVi": "Gửi tin nhắn."},
            {"word": "Share", "phonetic": "/ʃer/", "meaning": "Chia sẻ", "example": "Share a link.", "exampleVi": "Chia sẻ đường link."},
            {"word": "Like", "phonetic": "/laɪk/", "meaning": "Thích (nút like)", "example": "Give a like.", "exampleVi": "Bấm thích."},
            {"word": "Comment", "phonetic": "/ˈkɑː.ment/", "meaning": "Bình luận", "example": "Write a comment.", "exampleVi": "Viết bình luận."},
            {"word": "Follow", "phonetic": "/ˈfɑː.loʊ/", "meaning": "Theo dõi", "example": "Follow me.", "exampleVi": "Theo dõi tôi."},
            {"word": "Video", "phonetic": "/ˈvɪd.i.oʊ/", "meaning": "Video", "example": "Watch a video.", "exampleVi": "Xem video."},
            {"word": "Photo", "phonetic": "/ˈfoʊ.t̬oʊ/", "meaning": "Ảnh", "example": "Take a photo.", "exampleVi": "Chụp ảnh."}
        ],
        "listening": [{"en": "I will post a status update later.", "vi": "Tôi sẽ đăng cập nhật trạng thái sau."}, {"en": "She will send a message to her friend.", "vi": "Cô ấy sẽ gửi tin nhắn cho bạn mình."}, {"en": "Will you share this video on your wall?", "vi": "Bạn sẽ chia sẻ video này lên tường của mình chứ?"}, {"en": "They won't like your post if it's boring.", "vi": "Họ sẽ không thích bài đăng của bạn nếu nó nhàm chán."}, {"en": "I will comment on your photo.", "vi": "Tôi sẽ bình luận vào ảnh của bạn."}, {"en": "He will delete the old account.", "vi": "Anh ấy sẽ xóa tài khoản cũ."}, {"en": "The video will go viral soon.", "vi": "Video sẽ sớm trở nên phổ biến."}, {"en": "I won't follow him anymore.", "vi": "Tôi sẽ không theo dõi anh ta nữa."}, {"en": "She will take a lot of photos at the party.", "vi": "Cô ấy sẽ chụp rất nhiều ảnh tại bữa tiệc."}, {"en": "Check your messages, I sent a link.", "vi": "Kiểm tra tin nhắn đi, tôi đã gửi một đường link."}],
        "speaking": [{"en": "Do you use Instagram?", "vi": "Bạn có dùng Instagram không?"}, {"en": "Yes, I post photos there.", "vi": "Có, tôi đăng ảnh ở đó."}, {"en": "Did you see my new post?", "vi": "Bạn đã thấy bài đăng mới của tôi chưa?"}, {"en": "Yes, I liked it.", "vi": "Rồi, tôi đã thích nó rồi."}, {"en": "Can you share this link?", "vi": "Bạn có thể chia sẻ link này không?"}, {"en": "Sure, I'll do it now.", "vi": "Chắc chắn rồi, tôi sẽ làm ngay."}, {"en": "I'll send you a message.", "vi": "Tôi sẽ gửi tin nhắn cho bạn."}, {"en": "Okay, I'll check it later.", "vi": "Được rồi, tôi sẽ kiểm tra sau."}, {"en": "Don't write a mean comment.", "vi": "Đừng viết bình luận khiếm nhã."}, {"en": "I won't.", "vi": "Tôi sẽ không đâu."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will _____ a photo.", "answer": "post", "hint": "đăng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Send a _____.", "answer": "message", "hint": "tin nhắn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Share a _____.", "answer": "link", "hint": "đường liên kết"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Write a _____.", "answer": "comment", "hint": "bình luận"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ my account.", "answer": "Delete", "hint": "Xóa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I use _____ media.", "answer": "social", "hint": "xã hội (social...)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Give a _____.", "answer": "like", "hint": "thích"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ me on Twitter.", "answer": "Follow", "hint": "Theo dõi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Watch a _____.", "answer": "video", "hint": "video"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Take a _____.", "answer": "photo", "hint": "ảnh"}],
        "quizzes": [{"question": "'Message' nghĩa là gì?", "options": ["Tin nhắn", "Bài đăng", "Ảnh", "Video"], "correct": 0}, {"question": "I _____ post it later.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "She _____ not check it.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "Will you _____ the link?", "options": ["share", "shares", "sharing", "shared"], "correct": 0}, {"question": "I _____ delete my account.", "options": ["won't", "will", "am not", "don't"], "correct": 0}, {"question": "'Comment' nghĩa là gì?", "options": ["Bình luận", "Chia sẻ", "Thích", "Theo dõi"], "correct": 0}, {"question": "A _____ photo.", "options": ["new", "newly", "news", "newing"], "correct": 0}, {"question": "I'll _____ you a message.", "options": ["send", "sends", "sending", "sent"], "correct": 0}, {"question": "Follow _____ on Instagram.", "options": ["me", "I", "my", "mine"], "correct": 0}, {"question": "The video _____ go viral.", "options": ["will", "is", "are", "be"], "correct": 0}]
    },
    27: { # Dreams
        "grammar_affirmative": [{"en": "I will become a doctor.", "vi": "Tôi sẽ trở thành bác sĩ."}, {"en": "She will travel around the world.", "vi": "Cô ấy sẽ đi du lịch vòng quanh thế giới."}, {"en": "They will achieve their goals.", "vi": "Họ sẽ đạt được mục tiêu của mình."}],
        "grammar_negative": [{"en": "I won't give up.", "vi": "Tôi sẽ không bỏ cuộc."}, {"en": "He won't fail the exam.", "vi": "Anh ấy sẽ không trượt kỳ thi."}, {"en": "We won't forget our dreams.", "vi": "Chúng tôi sẽ không quên giấc mơ của mình."}],
        "vocabulary": [
            {"word": "Dream", "phonetic": "/driːm/", "meaning": "Ước mơ/Giấc mơ", "example": "Follow your dream.", "exampleVi": "Theo đuổi ước mơ."},
            {"word": "Goal", "phonetic": "/ɡoʊl/", "meaning": "Mục tiêu", "example": "Set a goal.", "exampleVi": "Đặt mục tiêu."},
            {"word": "Future", "phonetic": "/ˈfjuː.tʃɚ/", "meaning": "Tương lai", "example": "Think about the future.", "exampleVi": "Nghĩ về tương lai."},
            {"word": "Become", "phonetic": "/bɪˈkʌm/", "meaning": "Trở thành", "example": "Become famous.", "exampleVi": "Trở nên nổi tiếng."},
            {"word": "Success", "phonetic": "/səkˈses/", "meaning": "Thành công", "example": "Wish you success.", "exampleVi": "Chúc bạn thành công."},
            {"word": "Believe", "phonetic": "/bɪˈliːv/", "meaning": "Tin tưởng", "example": "Believe in yourself.", "exampleVi": "Tin vào chính mình."},
            {"word": "Work hard", "phonetic": "/wɝːk hɑːrd/", "meaning": "Làm việc chăm chỉ", "example": "I work hard.", "exampleVi": "Tôi làm việc chăm chỉ."},
            {"word": "Travel", "phonetic": "/ˈtræv.əl/", "meaning": "Du lịch", "example": "Travel the world.", "exampleVi": "Du lịch thế giới."},
            {"word": "Achieve", "phonetic": "/əˈtʃiːv/", "meaning": "Đạt được", "example": "Achieve success.", "exampleVi": "Đạt được thành công."},
            {"word": "Hope", "phonetic": "/hoʊp/", "meaning": "Hy vọng", "example": "I hope so.", "exampleVi": "Tôi hy vọng vậy."}
        ],
        "listening": [{"en": "I will work hard to achieve my dreams.", "vi": "Tôi sẽ làm việc chăm chỉ để đạt được ước mơ của mình."}, {"en": "She will become a famous singer one day.", "vi": "Một ngày nào đó cô ấy sẽ trở thành một ca sĩ nổi tiếng."}, {"en": "Will you travel around the world in the future?", "vi": "Trong tương lai bạn sẽ đi du lịch vòng quanh thế giới chứ?"}, {"en": "I won't give up until I succeed.", "vi": "Tôi sẽ không bỏ cuộc cho đến khi tôi thành công."}, {"en": "He will set a new goal for next year.", "vi": "Anh ấy sẽ đặt một mục tiêu mới cho năm tới."}, {"en": "Believe in yourself and you will win.", "vi": "Hãy tin vào chính mình và bạn sẽ chiến thắng."}, {"en": "They will find success in their business.", "vi": "Họ sẽ tìm thấy thành công trong công việc kinh doanh của mình."}, {"en": "I hope the future will be bright.", "vi": "Tôi hy vọng tương lai sẽ tươi sáng."}, {"en": "We won't forget our roots while dreaming big.", "vi": "Chúng tôi sẽ không quên cội nguồn trong khi mơ ước lớn lao."}, {"en": "What will you become when you grow up?", "vi": "Bạn sẽ trở thành gì khi lớn lên?"}],
        "speaking": [{"en": "What is your dream?", "vi": "Ước mơ của bạn là gì?"}, {"en": "I want to be a doctor.", "vi": "Tôi muốn trở thành bác sĩ."}, {"en": "That's a great goal.", "vi": "Đó là một mục tiêu tuyệt vời."}, {"en": "I'll work hard for it.", "vi": "Tôi sẽ làm việc chăm chỉ vì nó."}, {"en": "Will you travel the world?", "vi": "Bạn sẽ đi du lịch thế giới chứ?"}, {"en": "Yes, I will.", "vi": "Vâng, tôi sẽ đi."}, {"en": "Never give up!", "vi": "Đừng bao giờ bỏ cuộc!"}, {"en": "I won't.", "vi": "Tôi sẽ không đâu."}, {"en": "I believe in you.", "vi": "Tôi tin bạn."}, {"en": "Thank you for your support.", "vi": "Cảm ơn vì sự ủng hộ của bạn."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will _____ a doctor.", "answer": "become", "hint": "trở thành"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Follow your _____.", "answer": "dream", "hint": "ước mơ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Set a _____.", "answer": "goal", "hint": "mục tiêu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ in yourself.", "answer": "Believe", "hint": "Tin tưởng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ so.", "answer": "hope", "hint": "hy vọng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Work _____.", "answer": "hard", "hint": "chăm chỉ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Wish you _____.", "answer": "success", "hint": "thành công"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ the world.", "answer": "Travel", "hint": "Du lịch"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "In the _____.", "answer": "future", "hint": "tương lai"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I won't _____ up.", "answer": "give", "hint": "từ bỏ (give...)"}],
        "quizzes": [{"question": "'Dream' nghĩa là gì?", "options": ["Giấc mơ", "Thực tế", "Hiện tại", "Quá khứ"], "correct": 0}, {"question": "I _____ work hard.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "She _____ become famous.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "Will you _____ your goals?", "options": ["achieve", "achieves", "achieving", "achieved"], "correct": 0}, {"question": "I _____ give up.", "options": ["won't", "will", "am not", "don't"], "correct": 0}, {"question": "'Goal' nghĩa là gì?", "options": ["Mục tiêu", "Vạch xuất phát", "Kết quả", "Quá trình"], "correct": 0}, {"question": "Believe _____ yourself.", "options": ["in", "on", "at", "to"], "correct": 0}, {"question": "I'll _____ a pilot.", "options": ["become", "becoming", "becomes", "became"], "correct": 0}, {"question": "Wish you _____.", "options": ["success", "successful", "successfully", "succeed"], "correct": 0}, {"question": "The future _____ bright.", "options": ["will be", "be", "is", "do"], "correct": 0}]
    },
    28: { # Culture
        "grammar_affirmative": [{"en": "I will learn about traditions.", "vi": "Tôi sẽ tìm hiểu về các truyền thống."}, {"en": "She will visit historical places.", "vi": "Cô ấy sẽ đến thăm các địa điểm lịch sử."}, {"en": "They will respect the local culture.", "vi": "Họ sẽ tôn trọng văn hóa địa phương."}],
        "grammar_negative": [{"en": "I won't forget my roots.", "vi": "Tôi sẽ không quên cội nguồn của mình."}, {"en": "They won't change their customs.", "vi": "Họ sẽ không thay đổi phong tục của mình."}, {"en": "He won't ignore the rules.", "vi": "Anh ấy sẽ không phớt lờ các quy tắc."}],
        "vocabulary": [
            {"word": "Culture", "phonetic": "/ˈkʌl.tʃɚ/", "meaning": "Văn hóa", "example": "Local culture.", "exampleVi": "Văn hóa địa phương."},
            {"word": "Tradition", "phonetic": "/trəˈdɪʃ.ən/", "meaning": "Truyền thống", "example": "A long tradition.", "exampleVi": "Một truyền thống lâu đời."},
            {"word": "Custom", "phonetic": "/ˈkʌs.təm/", "meaning": "Phong tục", "example": "Follow customs.", "exampleVi": "Theo phong tục."},
            {"word": "History", "phonetic": "/ˈhɪs.t̬ɚ.i/", "meaning": "Lịch sử", "example": "Study history.", "exampleVi": "Học lịch sử."},
            {"word": "Art", "phonetic": "/ɑːrt/", "meaning": "Nghệ thuật", "example": "Modern art.", "exampleVi": "Nghệ thuật hiện đại."},
            {"word": "Music", "phonetic": "/ˈmjuː.zɪk/", "meaning": "Âm nhạc", "example": "Folk music.", "exampleVi": "Nhạc dân gian."},
            {"word": "Food", "phonetic": "/fuːd/", "meaning": "Thức ăn", "example": "Traditional food.", "exampleVi": "Thức ăn truyền thống."},
            {"word": "Respect", "phonetic": "/rɪˈspekt/", "meaning": "Tôn trọng", "example": "Respect others.", "exampleVi": "Tôn trọng người khác."},
            {"word": "Learn", "phonetic": "/lɝːn/", "meaning": "Học/Tìm hiểu", "example": "Learn new things.", "exampleVi": "Học những điều mới."},
            {"word": "World", "phonetic": "/wɝːld/", "meaning": "Thế giới", "example": "Around the world.", "exampleVi": "Vòng quanh thế giới."}
        ],
        "listening": [{"en": "We will explore the local culture together.", "vi": "Chúng ta sẽ cùng nhau khám phá văn hóa địa phương."}, {"en": "She will share stories about her traditions.", "vi": "Cô ấy sẽ chia sẻ những câu chuyện về truyền thống của mình."}, {"en": "They will respect the local customs and rules.", "vi": "Họ sẽ tôn trọng phong tục và quy tắc địa phương."}, {"en": "Will you try the traditional food there?", "vi": "Bạn sẽ thử đồ ăn truyền thống ở đó chứ?"}, {"en": "I will learn about the history of this city.", "vi": "Tôi sẽ tìm hiểu về lịch sử của thành phố này."}, {"en": "He won't forget where he came from.", "vi": "Anh ấy sẽ không quên nơi mình đã sinh ra."}, {"en": "The museum will show many works of art.", "vi": "Bảo tàng sẽ trưng bày nhiều tác phẩm nghệ thuật."}, {"en": "We will listen to traditional folk music.", "vi": "Chúng ta sẽ nghe nhạc dân gian truyền thống."}, {"en": "The world will be more connected in the future.", "vi": "Thế giới sẽ được kết nối nhiều hơn trong tương lai."}, {"en": "Always respect the culture of other people.", "vi": "Luôn luôn tôn trọng văn hóa của người khác."}],
        "speaking": [{"en": "What is your culture like?", "vi": "Văn hóa của bạn như thế nào?"}, {"en": "It's very rich and old.", "vi": "Nó rất phong phú và lâu đời."}, {"en": "Do you like traditional food?", "vi": "Bạn có thích món ăn truyền thống không?"}, {"en": "Yes, it's delicious.", "vi": "Có, nó rất ngon."}, {"en": "Will you visit the museum?", "vi": "Bạn sẽ đi thăm bảo tàng chứ?"}, {"en": "Yes, I want to see the art.", "vi": "Có, tôi muốn xem nghệ thuật."}, {"en": "It's important to respect customs.", "vi": "Tôn trọng phong tục là điều quan trọng."}, {"en": "I agree with you.", "vi": "Tôi đồng ý với bạn."}, {"en": "Let's learn together.", "vi": "Hãy cùng nhau tìm hiểu nhé."}, {"en": "Culture is beautiful.", "vi": "Văn hóa thật đẹp."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will learn about _____.", "answer": "culture", "hint": "văn hóa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Follow _____.", "answer": "tradition", "hint": "truyền thống"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Respect local _____.", "answer": "customs", "hint": "phong tục (số nhiều)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Study _____.", "answer": "history", "hint": "lịch sử"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Modern _____.", "answer": "art", "hint": "nghệ thuật"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Traditional _____.", "answer": "food", "hint": "thức ăn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ other people.", "answer": "Respect", "hint": "Tôn trọng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ new things.", "answer": "Learn", "hint": "Học/Tìm hiểu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Around the _____.", "answer": "world", "hint": "thế giới"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I won't _____ my roots.", "answer": "forget", "hint": "quên"}],
        "quizzes": [{"question": "'Culture' nghĩa là gì?", "options": ["Văn hóa", "Xã hội", "Kinh tế", "Chính trị"], "correct": 0}, {"question": "I _____ visit the museum.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "They _____ respect the rules.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "Will you _____ local food?", "options": ["try", "tries", "trying", "tried"], "correct": 0}, {"question": "I _____ forget my history.", "options": ["won't", "will", "am not", "don't"], "correct": 0}, {"question": "'History' nghĩa là gì?", "options": ["Lịch sử", "Địa lý", "Toán học", "Văn học"], "correct": 0}, {"question": "Traditional _____.", "options": ["music", "musically", "musician", "musics"], "correct": 0}, {"question": "I'll _____ about art.", "options": ["learn", "learning", "learns", "learned"], "correct": 0}, {"question": "Around the _____.", "options": ["world", "earth", "land", "city"], "correct": 0}, {"question": "Respect _____ others.", "options": ["for", "to", "at", "of"], "correct": 0}]
    }
}

for d in week4_data:
    update_lesson(d, week4_data[d])
print("Week 4 Batch 2 updated.")
