import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 2:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]
        lesson["tense"]["rules"][1]["examples"] = data["grammar_negative"]
    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week3_data = {
    15: { # Education
        "grammar_affirmative": [{"en": "I studied English yesterday.", "vi": "Tôi đã học tiếng Anh hôm qua."}, {"en": "She passed the exam.", "vi": "Cô ấy đã vượt qua kỳ thi."}, {"en": "They graduated last year.", "vi": "Họ đã tốt nghiệp năm ngoái."}],
        "grammar_negative": [{"en": "I didn't go to school.", "vi": "Tôi đã không đi học."}, {"en": "He didn't finish his homework.", "vi": "Anh ấy đã không hoàn thành bài tập."}, {"en": "We didn't see the teacher.", "vi": "Chúng tôi đã không gặp giáo viên."}],
        "vocabulary": [
            {"word": "School", "phonetic": "/skuːl/", "meaning": "Trường học", "example": "Go to school.", "exampleVi": "Đi học."},
            {"word": "Teacher", "phonetic": "/ˈtiː.tʃɚ/", "meaning": "Giáo viên", "example": "My teacher is kind.", "exampleVi": "Giáo viên tôi tốt bụng."},
            {"word": "Student", "phonetic": "/ˈstuː.dənt/", "meaning": "Học sinh", "example": "A hardworking student.", "exampleVi": "Một học sinh chăm chỉ."},
            {"word": "Classroom", "phonetic": "/ˈklæs.ruːm/", "meaning": "Lớp học", "example": "The classroom is big.", "exampleVi": "Lớp học lớn."},
            {"word": "Lesson", "phonetic": "/ˈles.ən/", "meaning": "Bài học", "example": "A difficult lesson.", "exampleVi": "Một bài học khó."},
            {"word": "Exam", "phonetic": "/ɪɡˈzæm/", "meaning": "Kỳ thi", "example": "Study for the exam.", "exampleVi": "Học cho kỳ thi."},
            {"word": "Book", "phonetic": "/bʊk/", "meaning": "Quyển sách", "example": "Read a book.", "exampleVi": "Đọc sách."},
            {"word": "Pen", "phonetic": "/pen/", "meaning": "Bút mực", "example": "Write with a pen.", "exampleVi": "Viết bằng bút mực."},
            {"word": "University", "phonetic": "/ˌjuː.nəˈvɝː.sə.t̬i/", "meaning": "Trường đại học", "example": "Go to university.", "exampleVi": "Vào đại học."},
            {"word": "Study", "phonetic": "/ˈstʌd.i/", "meaning": "Học tập", "example": "Study hard.", "exampleVi": "Học tập chăm chỉ."}
        ],
        "listening": [{"en": "I went to school by bus yesterday.", "vi": "Hôm qua tôi đã đi học bằng xe buýt."}, {"en": "Did you finish your homework?", "vi": "Bạn đã làm xong bài tập chưa?"}, {"en": "She studied very hard for the exam.", "vi": "Cô ấy đã học rất chăm chỉ cho kỳ thi."}, {"en": "The teacher explained the lesson clearly.", "vi": "Giáo viên đã giải thích bài học một cách rõ ràng."}, {"en": "We graduated from university in June.", "vi": "Chúng tôi đã tốt nghiệp đại học vào tháng Sáu."}, {"en": "He didn't pass the math test.", "vi": "Anh ấy đã không vượt qua bài kiểm tra toán."}, {"en": "I bought a new book last week.", "vi": "Tôi đã mua một cuốn sách mới tuần trước."}, {"en": "Were you in the classroom yesterday?", "vi": "Hôm qua bạn có ở trong lớp không?"}, {"en": "The students were very quiet.", "vi": "Các học sinh đã rất im lặng."}, {"en": "I learned many new words today.", "vi": "Hôm nay tôi đã học được nhiều từ mới."}],
        "speaking": [{"en": "Did you study last night?", "vi": "Tối qua bạn có học không?"}, {"en": "Yes, I studied for two hours.", "vi": "Có, tôi đã học trong hai tiếng."}, {"en": "How was the exam?", "vi": "Kỳ thi thế nào?"}, {"en": "It was very difficult.", "vi": "Nó đã rất khó."}, {"en": "I didn't see you at school.", "vi": "Tôi đã không thấy bạn ở trường."}, {"en": "I was sick yesterday.", "vi": "Hôm qua tôi đã bị ốm."}, {"en": "What did you learn today?", "vi": "Hôm nay bạn đã học gì?"}, {"en": "We learned about history.", "vi": "Chúng tôi đã học về lịch sử."}, {"en": "That's interesting!", "vi": "Thật thú vị!"}, {"en": "Good job!", "vi": "Làm tốt lắm!"}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ English yesterday.", "answer": "studied", "hint": "đã học"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She _____ the exam.", "answer": "passed", "hint": "đã vượt qua"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ to school.", "answer": "went", "hint": "đã đi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Did you _____ your homework?", "answer": "finish", "hint": "hoàn thành (dùng sau did)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The _____ was difficult.", "answer": "lesson", "hint": "bài học"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A hardworking _____.", "answer": "student", "hint": "học sinh"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "They _____ last year.", "answer": "graduated", "hint": "đã tốt nghiệp"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Read a _____.", "answer": "book", "hint": "quyển sách"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Write with a _____.", "answer": "pen", "hint": "cái bút"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The _____ was kind.", "answer": "teacher", "hint": "giáo viên"}],
        "quizzes": [{"question": "'University' nghĩa là gì?", "options": ["Trường cấp 1", "Trường cấp 2", "Trường cấp 3", "Trường đại học"], "correct": 3}, {"question": "I _____ a new book yesterday.", "options": ["buy", "bought", "buys", "buying"], "correct": 1}, {"question": "She _____ not go to school.", "options": ["did", "does", "is", "was"], "correct": 0}, {"question": "Did you _____ the lesson?", "options": ["understand", "understood", "understands", "understanding"], "correct": 0}, {"question": "They _____ students last year.", "options": ["was", "were", "is", "are"], "correct": 1}, {"question": "The exam _____ very easy.", "options": ["is", "was", "were", "did"], "correct": 1}, {"question": "'Graduated' nghĩa là gì?", "options": ["Nhập học", "Tốt nghiệp", "Bỏ học", "Nghỉ học"], "correct": 1}, {"question": "I _____ see the teacher.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "Where _____ you yesterday?", "options": ["did", "was", "were", "do"], "correct": 2}, {"question": "He _____ hard for the test.", "options": ["study", "studies", "studied", "studying"], "correct": 2}]
    },
    16: { # Technology
        "grammar_affirmative": [{"en": "I bought a new phone.", "vi": "Tôi đã mua một chiếc điện thoại mới."}, {"en": "He used the internet.", "vi": "Anh ấy đã sử dụng internet."}, {"en": "They fixed the computer.", "vi": "Họ đã sửa chiếc máy tính."}],
        "grammar_negative": [{"en": "I didn't send the email.", "vi": "Tôi đã không gửi email."}, {"en": "She didn't watch the video.", "vi": "Cô ấy đã không xem video."}, {"en": "The app didn't work.", "vi": "Ứng dụng đã không hoạt động."}],
        "vocabulary": [
            {"word": "Computer", "phonetic": "/kəmˈpjuː.t̬ɚ/", "meaning": "Máy tính", "example": "Use a computer.", "exampleVi": "Sử dụng máy tính."},
            {"word": "Phone", "phonetic": "/foʊn/", "meaning": "Điện thoại", "example": "Call me on my phone.", "exampleVi": "Gọi cho tôi qua điện thoại."},
            {"word": "Internet", "phonetic": "/ˈɪn.t̬ɚ.net/", "meaning": "Internet/Mạng", "example": "Search the internet.", "exampleVi": "Tìm kiếm trên mạng."},
            {"word": "Website", "phonetic": "/ˈweb.saɪt/", "meaning": "Trang web", "example": "Visit a website.", "exampleVi": "Truy cập trang web."},
            {"word": "Email", "phonetic": "/ˈiː.meɪl/", "meaning": "Thư điện tử", "example": "Send an email.", "exampleVi": "Gửi một email."},
            {"word": "App", "phonetic": "/æp/", "meaning": "Ứng dụng", "example": "Download an app.", "exampleVi": "Tải một ứng dụng."},
            {"word": "Screen", "phonetic": "/skriːn/", "meaning": "Màn hình", "example": "A broken screen.", "exampleVi": "Một màn hình bị vỡ."},
            {"word": "Mouse", "phonetic": "/maʊs/", "meaning": "Chuột máy tính", "example": "Click the mouse.", "exampleVi": "Bấm chuột."},
            {"word": "Keyboard", "phonetic": "/ˈkiː.bɔːrd/", "meaning": "Bàn phím", "example": "Type on the keyboard.", "exampleVi": "Gõ bàn phím."},
            {"word": "Laptop", "phonetic": "/ˈlæp.tɑːp/", "meaning": "Máy tính xách tay", "example": "Bring your laptop.", "exampleVi": "Mang theo laptop của bạn."}
        ],
        "listening": [{"en": "I bought a new laptop yesterday.", "vi": "Hôm qua tôi đã mua một chiếc laptop mới."}, {"en": "Did you check your email this morning?", "vi": "Sáng nay bạn đã kiểm tra email chưa?"}, {"en": "The internet was very slow last night.", "vi": "Tối qua mạng rất chậm."}, {"en": "He downloaded a new game app.", "vi": "Anh ấy đã tải một ứng dụng trò chơi mới."}, {"en": "She broke the screen of her phone.", "vi": "Cô ấy đã làm vỡ màn hình điện thoại."}, {"en": "I sent you a message an hour ago.", "vi": "Tôi đã gửi tin nhắn cho bạn một giờ trước."}, {"en": "The website didn't load properly.", "vi": "Trang web đã không tải được bình thường."}, {"en": "We used the computer to finish the work.", "vi": "Chúng tôi đã dùng máy tính để hoàn thành công việc."}, {"en": "He fixed my keyboard yesterday.", "vi": "Anh ấy đã sửa bàn phím của tôi hôm qua."}, {"en": "Did they watch the video online?", "vi": "Họ có xem video trực tuyến không?"}],
        "speaking": [{"en": "My phone is broken.", "vi": "Điện thoại của tôi bị hỏng rồi."}, {"en": "What happened?", "vi": "Chuyện gì đã xảy ra vậy?"}, {"en": "I dropped it on the floor.", "vi": "Tôi làm rơi nó xuống sàn."}, {"en": "Did you fix it?", "vi": "Bạn đã sửa nó chưa?"}, {"en": "Not yet.", "vi": "Chưa."}, {"en": "I need a new computer.", "vi": "Tôi cần một chiếc máy tính mới."}, {"en": "The internet is not working.", "vi": "Mạng không hoạt động."}, {"en": "Did you restart the router?", "vi": "Bạn đã khởi động lại bộ định tuyến chưa?"}, {"en": "Yes, I did.", "vi": "Vâng, tôi đã làm rồi."}, {"en": "Let me check.", "vi": "Để tôi kiểm tra xem."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ a new phone.", "answer": "bought", "hint": "đã mua"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He _____ the internet.", "answer": "used", "hint": "đã dùng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ an email.", "answer": "sent", "hint": "đã gửi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The _____ is slow.", "answer": "internet", "hint": "mạng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A broken _____.", "answer": "screen", "hint": "màn hình"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Download an _____.", "answer": "app", "hint": "ứng dụng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Type on the _____.", "answer": "keyboard", "hint": "bàn phím"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Visit a _____.", "answer": "website", "hint": "trang web"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Bring your _____.", "answer": "laptop", "hint": "máy tính xách tay"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The _____ worked.", "answer": "computer", "hint": "máy tính"}],
        "quizzes": [{"question": "'Website' nghĩa là gì?", "options": ["Trang web", "Email", "Ứng dụng", "Màn hình"], "correct": 0}, {"question": "I _____ a new app last night.", "options": ["download", "downloaded", "downloads", "downloading"], "correct": 1}, {"question": "He _____ not use the phone.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "Did you _____ the message?", "options": ["receive", "received", "receives", "receiving"], "correct": 0}, {"question": "The screen _____ broken yesterday.", "options": ["is", "was", "were", "did"], "correct": 1}, {"question": "I _____ you an email.", "options": ["send", "sent", "sends", "sending"], "correct": 1}, {"question": "'Laptop' là loại máy gì?", "options": ["Để bàn", "Xách tay", "Cầm tay", "Máy tính bảng"], "correct": 1}, {"question": "The internet _____ slow.", "options": ["was", "were", "did", "am"], "correct": 0}, {"question": "Did she _____ the computer?", "options": ["fix", "fixed", "fixes", "fixing"], "correct": 0}, {"question": "They _____ not send it.", "options": ["did", "do", "was", "were"], "correct": 0}]
    },
    17: { # Animals
        "grammar_affirmative": [{"en": "I saw a big elephant.", "vi": "Tôi đã thấy một con voi lớn."}, {"en": "The dog barked at me.", "vi": "Con chó đã sủa tôi."}, {"en": "They visited the zoo.", "vi": "Họ đã đi thăm sở thú."}],
        "grammar_negative": [{"en": "I didn't see any lions.", "vi": "Tôi đã không thấy con sư tử nào."}, {"en": "The cat didn't eat the fish.", "vi": "Con mèo đã không ăn cá."}, {"en": "We didn't catch the bird.", "vi": "Chúng tôi đã không bắt được con chim."}],
        "vocabulary": [
            {"word": "Animal", "phonetic": "/ˈæn.ɪ.məl/", "meaning": "Động vật", "example": "I like animals.", "exampleVi": "Tôi thích động vật."},
            {"word": "Dog", "phonetic": "/dɔːɡ/", "meaning": "Con chó", "example": "A loyal dog.", "exampleVi": "Một con chó trung thành."},
            {"word": "Cat", "phonetic": "/kæt/", "meaning": "Con mèo", "example": "A cute cat.", "exampleVi": "Một con mèo đáng yêu."},
            {"word": "Elephant", "phonetic": "/ˈel.ə.fənt/", "meaning": "Con voi", "example": "A big elephant.", "exampleVi": "Một con voi lớn."},
            {"word": "Lion", "phonetic": "/ˈlaɪ.ən/", "meaning": "Con sư tử", "example": "A brave lion.", "exampleVi": "Một con sư tử dũng cảm."},
            {"word": "Bird", "phonetic": "/bɝːd/", "meaning": "Con chim", "example": "A small bird.", "exampleVi": "Một con chim nhỏ."},
            {"word": "Fish", "phonetic": "/fɪʃ/", "meaning": "Con cá", "example": "A colorful fish.", "exampleVi": "Một con cá nhiều màu sắc."},
            {"word": "Tiger", "phonetic": "/ˈtaɪ.ɡɚ/", "meaning": "Con hổ", "example": "A dangerous tiger.", "exampleVi": "Một con hổ nguy hiểm."},
            {"word": "Zoo", "phonetic": "/zuː/", "meaning": "Sở thú", "example": "Go to the zoo.", "exampleVi": "Đi sở thú."},
            {"word": "Pet", "phonetic": "/pet/", "meaning": "Thú cưng", "example": "I have a pet.", "exampleVi": "Tôi có một con thú cưng."}
        ],
        "listening": [{"en": "We went to the zoo yesterday.", "vi": "Hôm qua chúng tôi đã đi sở thú."}, {"en": "I saw a lot of animals there.", "vi": "Tôi đã thấy rất nhiều động vật ở đó."}, {"en": "The elephant was very large.", "vi": "Con voi đã rất to lớn."}, {"en": "Did you see the lions?", "vi": "Bạn có thấy những con sư tử không?"}, {"en": "My dog barked at the neighbor.", "vi": "Con chó của tôi đã sủa người hàng xóm."}, {"en": "The cat slept on the sofa all day.", "vi": "Con mèo đã ngủ trên sofa cả ngày."}, {"en": "We fed the birds in the park.", "vi": "Chúng tôi đã cho chim ăn trong công viên."}, {"en": "He caught a big fish last weekend.", "vi": "Anh ấy đã bắt được một con cá lớn vào cuối tuần trước."}, {"en": "The tiger was sleeping in the cage.", "vi": "Con hổ đang ngủ trong chuồng."}, {"en": "I didn't have a pet when I was young.", "vi": "Tôi không có thú cưng khi tôi còn nhỏ."}],
        "speaking": [{"en": "Do you like animals?", "vi": "Bạn có thích động vật không?"}, {"en": "Yes, I love dogs.", "vi": "Có, tôi yêu chó."}, {"en": "Do you have a pet?", "vi": "Bạn có thú cưng không?"}, {"en": "Yes, I have a cat.", "vi": "Có, tôi có một con mèo."}, {"en": "What did you see at the zoo?", "vi": "Bạn đã thấy gì ở sở thú?"}, {"en": "I saw an elephant.", "vi": "Tôi đã thấy một con voi."}, {"en": "Was it big?", "vi": "Nó có to không?"}, {"en": "Yes, very big!", "vi": "Có, rất to!"}, {"en": "I am afraid of tigers.", "vi": "Tôi sợ hổ lắm."}, {"en": "Me too.", "vi": "Tôi cũng vậy."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ a lion at the zoo.", "answer": "saw", "hint": "đã thấy"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The dog _____ at me.", "answer": "barked", "hint": "đã sủa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A big _____.", "answer": "elephant", "hint": "con voi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A cute _____.", "answer": "cat", "hint": "con mèo"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "We went to the _____.", "answer": "zoo", "hint": "sở thú"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I have a _____.", "answer": "pet", "hint": "thú cưng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A colorful _____.", "answer": "fish", "hint": "con cá"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A dangerous _____.", "answer": "tiger", "hint": "con hổ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A small _____.", "answer": "bird", "hint": "con chim"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ like animals.", "answer": "didn't", "hint": "đã không"}],
        "quizzes": [{"question": "'Elephant' là con gì?", "options": ["Hổ", "Sư tử", "Voi", "Chó"], "correct": 2}, {"question": "I _____ a dog yesterday.", "options": ["see", "saw", "sees", "seeing"], "correct": 1}, {"question": "The cat _____ not eat.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "Did you _____ to the zoo?", "options": ["go", "went", "goes", "going"], "correct": 0}, {"question": "They _____ happy to see us.", "options": ["was", "were", "did", "do"], "correct": 1}, {"question": "The lion _____ very loud.", "options": ["roar", "roared", "roars", "roaring"], "correct": 1}, {"question": "'Zoo' nghĩa là gì?", "options": ["Sở thú", "Công viên", "Bảo tàng", "Trường học"], "correct": 0}, {"question": "I _____ have a pet.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "We _____ the birds.", "options": ["feed", "fed", "feeds", "feeding"], "correct": 1}, {"question": "A loyal _____.", "options": ["dog", "cat", "bird", "fish"], "correct": 0}]
    }
}

for d in week3_data:
    update_lesson(d, week3_data[d])
print("Week 3 Batch 1 updated.")
