import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 2:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]
        lesson["tense"]["rules"][1]["examples"] = data["grammar_negative"]
    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week4_data = {
    22: { # City Life
        "grammar_affirmative": [{"en": "I will move to a big city.", "vi": "Tôi sẽ chuyển đến một thành phố lớn."}, {"en": "The city will be more modern.", "vi": "Thành phố sẽ hiện đại hơn."}, {"en": "We will take the subway.", "vi": "Chúng tôi sẽ đi tàu điện ngầm."}],
        "grammar_negative": [{"en": "He won't live in the countryside.", "vi": "Anh ấy sẽ không sống ở nông thôn."}, {"en": "There won't be much traffic.", "vi": "Sẽ không có nhiều giao thông (tắc nghẽn)."}, {"en": "I won't stay out late.", "vi": "Tôi sẽ không ở ngoài muộn."}],
        "vocabulary": [
            {"word": "City", "phonetic": "/ˈsɪt.i/", "meaning": "Thành phố", "example": "A busy city.", "exampleVi": "Thành phố nhộn nhịp."},
            {"word": "Subway", "phonetic": "/ˈsʌb.weɪ/", "meaning": "Tàu điện ngầm", "example": "Take the subway.", "exampleVi": "Đi tàu điện ngầm."},
            {"word": "Traffic", "phonetic": "/ˈtræf.ɪk/", "meaning": "Giao thông", "example": "Heavy traffic.", "exampleVi": "Giao thông đông đúc."},
            {"word": "Building", "phonetic": "/ˈbɪl.dɪŋ/", "meaning": "Tòa nhà", "example": "A tall building.", "exampleVi": "Một tòa nhà cao tầng."},
            {"word": "Street", "phonetic": "/striːt/", "meaning": "Con phố", "example": "Cross the street.", "exampleVi": "Băng qua đường."},
            {"word": "Park", "phonetic": "/pɑːrk/", "meaning": "Công viên", "example": "Meet in the park.", "exampleVi": "Gặp nhau ở công viên."},
            {"word": "Library", "phonetic": "/ˈlaɪ.brer.i/", "meaning": "Thư viện", "example": "Go to the library.", "exampleVi": "Đi thư viện."},
            {"word": "Center", "phonetic": "/ˈsen.t̬ɚ/", "meaning": "Trung tâm", "example": "City center.", "exampleVi": "Trung tâm thành phố."},
            {"word": "Modern", "phonetic": "/ˈmɑː.dɚn/", "meaning": "Hiện đại", "example": "A modern city.", "exampleVi": "Một thành phố hiện đại."},
            {"word": "Crowded", "phonetic": "/ˈkraʊ.dɪd/", "meaning": "Đông đúc", "example": "A crowded place.", "exampleVi": "Một nơi đông đúc."}
        ],
        "listening": [{"en": "I will visit the city center tomorrow.", "vi": "Tôi sẽ đến thăm trung tâm thành phố vào ngày mai."}, {"en": "The subway will be very crowded.", "vi": "Tàu điện ngầm sẽ rất đông đúc."}, {"en": "We will see many tall buildings.", "vi": "Chúng ta sẽ thấy nhiều tòa nhà cao tầng."}, {"en": "He will find a job in the city.", "vi": "Anh ấy sẽ tìm được một công việc ở thành phố."}, {"en": "There will be new parks for children.", "vi": "Sẽ có những công viên mới cho trẻ em."}, {"en": "I won't take the bus, I'll walk.", "vi": "Tôi sẽ không đi xe buýt, tôi sẽ đi bộ."}, {"en": "Will you move to a new apartment?", "vi": "Bạn sẽ chuyển đến một căn hộ mới chứ?"}, {"en": "The traffic won't be a problem.", "vi": "Giao thông sẽ không phải là một vấn đề."}, {"en": "She will study at the central library.", "vi": "Cô ấy sẽ học tại thư viện trung tâm."}, {"en": "The city will look beautiful at night.", "vi": "Thành phố sẽ trông rất đẹp vào ban đêm."}],
        "speaking": [{"en": "Where will you go tomorrow?", "vi": "Ngày mai bạn sẽ đi đâu?"}, {"en": "I'll go to the city center.", "vi": "Tôi sẽ đến trung tâm thành phố."}, {"en": "Will you take the subway?", "vi": "Bạn sẽ đi tàu điện ngầm chứ?"}, {"en": "Yes, it's faster.", "vi": "Vâng, nó nhanh hơn."}, {"en": "Is the city crowded?", "vi": "Thành phố có đông đúc không?"}, {"en": "Yes, very crowded.", "vi": "Có, rất đông đúc."}, {"en": "I like modern buildings.", "vi": "Tôi thích những tòa nhà hiện đại."}, {"en": "I'll meet you in the park.", "vi": "Tôi sẽ gặp bạn ở công viên."}, {"en": "Don't be late!", "vi": "Đừng đến muộn nhé!"}, {"en": "I won't.", "vi": "Tôi sẽ không đâu."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will _____ to the city.", "answer": "move", "hint": "chuyển (đến)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Take the _____.", "answer": "subway", "hint": "tàu điện ngầm"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A tall _____.", "answer": "building", "hint": "tòa nhà"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A busy _____.", "answer": "street", "hint": "con phố"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Heavy _____.", "answer": "traffic", "hint": "giao thông"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A _____ city.", "answer": "modern", "hint": "hiện đại"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Meet in the _____.", "answer": "park", "hint": "công viên"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go to the _____.", "answer": "library", "hint": "thư viện"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "City _____.", "answer": "center", "hint": "trung tâm"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A _____ place.", "answer": "crowded", "hint": "đông đúc"}],
        "quizzes": [{"question": "'Subway' là phương tiện gì?", "options": ["Xe buýt", "Tàu điện ngầm", "Taxi", "Máy bay"], "correct": 1}, {"question": "I _____ visit you tomorrow.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "They _____ not move next year.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "Will you _____ the bus?", "options": ["take", "takes", "taking", "taken"], "correct": 0}, {"question": "The building _____ be tall.", "options": ["will", "won't", "is", "be"], "correct": 0}, {"question": "There _____ be a lot of traffic.", "options": ["will", "is", "are", "do"], "correct": 0}, {"question": "'Modern' nghĩa là gì?", "options": ["Cổ kính", "Hiện đại", "Đông đúc", "Yên tĩnh"], "correct": 1}, {"question": "I _____ stay out late.", "options": ["won't", "will", "am not", "don't"], "correct": 0}, {"question": "Where _____ you go?", "options": ["will", "shall", "do", "are"], "correct": 0}, {"question": "A _____ street.", "options": ["busy", "busily", "modern", "crowded"], "correct": 0}]
    },
    23: { # Nature
        "grammar_affirmative": [{"en": "We will plant many trees.", "vi": "Chúng tôi sẽ trồng nhiều cây."}, {"en": "The weather will be sunny.", "vi": "Thời tiết sẽ có nắng."}, {"en": "I will go for a walk in the forest.", "vi": "Tôi sẽ đi bộ trong rừng."}],
        "grammar_negative": [{"en": "It won't rain tomorrow.", "vi": "Ngày mai trời sẽ không mưa."}, {"en": "They won't cut down the forest.", "vi": "Họ sẽ không chặt phá khu rừng."}, {"en": "I won't pollute the environment.", "vi": "Tôi sẽ không gây ô nhiễm môi trường."}],
        "vocabulary": [
            {"word": "Nature", "phonetic": "/ˈneɪ.tʃɚ/", "meaning": "Thiên nhiên", "example": "Protect nature.", "exampleVi": "Bảo vệ thiên nhiên."},
            {"word": "Tree", "phonetic": "/triː/", "meaning": "Cái cây", "example": "Plant a tree.", "exampleVi": "Trồng một cái cây."},
            {"word": "Flower", "phonetic": "/ˈflaʊ.ɚ/", "meaning": "Bông hoa", "example": "A beautiful flower.", "exampleVi": "Một bông hoa đẹp."},
            {"word": "Forest", "phonetic": "/ˈfɔːr.ɪst/", "meaning": "Khu rừng", "example": "Walk in the forest.", "exampleVi": "Đi dạo trong rừng."},
            {"word": "Mountain", "phonetic": "/ˈmaʊn.tən/", "meaning": "Ngọn núi", "example": "Climb a mountain.", "exampleVi": "Leo núi."},
            {"word": "River", "phonetic": "/ˈrɪv.ɚ/", "meaning": "Con sông", "example": "Swim in the river.", "exampleVi": "Bơi ở sông."},
            {"word": "Sea", "phonetic": "/siː/", "meaning": "Biển", "example": "Blue sea.", "exampleVi": "Biển xanh."},
            {"word": "Environment", "phonetic": "/ɪnˈvaɪ.rən.mənt/", "meaning": "Môi trường", "example": "Clean environment.", "exampleVi": "Môi trường sạch."},
            {"word": "Plant", "phonetic": "/plænt/", "meaning": "Thực vật/Trồng", "example": "A green plant.", "exampleVi": "Một loài thực vật xanh."},
            {"word": "Earth", "phonetic": "/ɝːθ/", "meaning": "Trái đất", "example": "Save the Earth.", "exampleVi": "Cứu lấy Trái đất."}
        ],
        "listening": [{"en": "We will plant more trees to protect the Earth.", "vi": "Chúng tôi sẽ trồng thêm cây để bảo vệ Trái đất."}, {"en": "The weather will be perfect for a hike.", "vi": "Thời tiết sẽ hoàn hảo cho một buổi đi bộ đường dài."}, {"en": "Will you go to the beach next summer?", "vi": "Mùa hè tới bạn sẽ đi biển chứ?"}, {"en": "They won't pollute the river anymore.", "vi": "Họ sẽ không làm ô nhiễm con sông nữa."}, {"en": "I will see many beautiful flowers in the park.", "vi": "Tôi sẽ thấy nhiều bông hoa đẹp trong công viên."}, {"en": "The forest will be very quiet and peaceful.", "vi": "Khu rừng sẽ rất yên tĩnh và thanh bình."}, {"en": "We will save the environment together.", "vi": "Chúng ta sẽ cùng nhau cứu lấy môi trường."}, {"en": "It won't be cold tomorrow.", "vi": "Ngày mai trời sẽ không lạnh."}, {"en": "She will climb the mountain next month.", "vi": "Cô ấy sẽ leo núi vào tháng tới."}, {"en": "The sea will be blue and clear.", "vi": "Biển sẽ xanh và trong."}],
        "speaking": [{"en": "I love nature.", "vi": "Tôi yêu thiên nhiên."}, {"en": "Me too, it's beautiful.", "vi": "Tôi cũng vậy, nó thật đẹp."}, {"en": "Will you plant a tree?", "vi": "Bạn sẽ trồng một cái cây chứ?"}, {"en": "Yes, I will.", "vi": "Vâng, tôi sẽ làm vậy."}, {"en": "The river is very clean.", "vi": "Con sông rất sạch."}, {"en": "Let's go to the forest.", "vi": "Chúng ta hãy đi vào rừng nào."}, {"en": "Is it far?", "vi": "Nó có xa không?"}, {"en": "No, it's nearby.", "vi": "Không, nó ở ngay gần đây."}, {"en": "The mountains are high.", "vi": "Những ngọn núi thật cao."}, {"en": "Earth is our home.", "vi": "Trái đất là nhà của chúng ta."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "We will _____ trees.", "answer": "plant", "hint": "trồng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Protect _____.", "answer": "nature", "hint": "thiên nhiên"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A beautiful _____.", "answer": "flower", "hint": "bông hoa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "In the _____.", "answer": "forest", "hint": "khu rừng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "High _____.", "answer": "mountain", "hint": "ngọn núi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Blue _____.", "answer": "sea", "hint": "biển"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Save the _____.", "answer": "Earth", "hint": "Trái đất"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Clean _____.", "answer": "environment", "hint": "môi trường"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Green _____.", "answer": "plant", "hint": "thực vật"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Swim in the _____.", "answer": "river", "hint": "con sông"}],
        "quizzes": [{"question": "'Earth' nghĩa là gì?", "options": ["Mặt trăng", "Mặt trời", "Trái đất", "Sao hỏa"], "correct": 2}, {"question": "We _____ protect nature.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "It _____ rain tomorrow.", "options": ["won't", "will", "is", "does"], "correct": 0}, {"question": "She _____ climb the mountain.", "options": ["will", "shall", "is", "be"], "correct": 0}, {"question": "They _____ not cut the trees.", "options": ["will", "won't", "do", "does"], "correct": 0}, {"question": "'Forest' nghĩa là gì?", "options": ["Rừng", "Biển", "Sông", "Núi"], "correct": 0}, {"question": "A green _____.", "options": ["plant", "planting", "plants", "planted"], "correct": 0}, {"question": "Will you _____ trees?", "options": ["plant", "plants", "planting", "planted"], "correct": 0}, {"question": "The sea _____ blue.", "options": ["will be", "be", "is", "are"], "correct": 0}, {"question": "Protect _____ environment.", "options": ["the", "a", "an", "some"], "correct": 0}]
    },
    24: { # Festivals
        "grammar_affirmative": [{"en": "I will celebrate the New Year.", "vi": "Tôi sẽ ăn mừng năm mới."}, {"en": "She will wear a new dress.", "vi": "Cô ấy sẽ mặc một chiếc váy mới."}, {"en": "We will have a big party.", "vi": "Chúng tôi sẽ có một bữa tiệc lớn."}],
        "grammar_negative": [{"en": "I won't buy fireworks.", "vi": "Tôi sẽ không mua pháo hoa."}, {"en": "They won't stay home.", "vi": "Họ sẽ không ở nhà."}, {"en": "He won't miss the parade.", "vi": "Anh ấy sẽ không lỡ buổi diễu hành."}],
        "vocabulary": [
            {"word": "Festival", "phonetic": "/ˈfes.tə.vəl/", "meaning": "Lễ hội", "example": "A traditional festival.", "exampleVi": "Một lễ hội truyền thống."},
            {"word": "Celebrate", "phonetic": "/ˈsel.ə.breɪt/", "meaning": "Kỷ niệm/Ăn mừng", "example": "Celebrate a birthday.", "exampleVi": "Ăn mừng sinh nhật."},
            {"word": "Party", "phonetic": "/ˈpɑːr.t̬i/", "meaning": "Bữa tiệc", "example": "Go to a party.", "exampleVi": "Đi dự tiệc."},
            {"word": "Gift", "phonetic": "/ɡɪft/", "meaning": "Quà tặng", "example": "Give a gift.", "exampleVi": "Tặng một món quà."},
            {"word": "Fireworks", "phonetic": "/ˈfaɪr.wɝːks/", "meaning": "Pháo hoa", "example": "Watch fireworks.", "exampleVi": "Xem pháo hoa."},
            {"word": "Parade", "phonetic": "/pəˈreɪd/", "meaning": "Diễu hành", "example": "A street parade.", "exampleVi": "Một cuộc diễu hành đường phố."},
            {"word": "Holiday", "phonetic": "/ˈhɑː.lə.deɪ/", "meaning": "Ngày nghỉ lễ", "example": "Enjoy the holiday.", "exampleVi": "Tận hưởng ngày nghỉ."},
            {"word": "Tradition", "phonetic": "/trəˈdɪʃ.ən/", "meaning": "Truyền thống", "example": "Follow tradition.", "exampleVi": "Theo truyền thống."},
            {"word": "New Year", "phonetic": "/ˌnuː ˈjɪr/", "meaning": "Năm mới", "example": "Happy New Year!", "exampleVi": "Chúc mừng năm mới!"},
            {"word": "Music", "phonetic": "/ˈmjuː.zɪk/", "meaning": "Âm nhạc", "example": "Play loud music.", "exampleVi": "Chơi nhạc lớn."}
        ],
        "listening": [{"en": "We will celebrate the festival together.", "vi": "Chúng ta sẽ cùng nhau ăn mừng lễ hội."}, {"en": "There will be a big parade in the city center.", "vi": "Sẽ có một buổi diễu hành lớn ở trung tâm thành phố."}, {"en": "I will give my mother a special gift.", "vi": "Tôi sẽ tặng mẹ một món quà đặc biệt."}, {"en": "Will you watch the fireworks tonight?", "vi": "Bạn sẽ xem pháo hoa tối nay chứ?"}, {"en": "They won't work during the holiday.", "vi": "Họ sẽ không làm việc trong kỳ nghỉ lễ."}, {"en": "She will wear a beautiful traditional dress.", "vi": "Cô ấy sẽ mặc một chiếc váy truyền thống tuyệt đẹp."}, {"en": "The party will start at 8 PM.", "vi": "Bữa tiệc sẽ bắt đầu lúc 8 giờ tối."}, {"en": "We will enjoy some great music.", "vi": "Chúng ta sẽ thưởng thức những bản nhạc tuyệt vời."}, {"en": "He will come to the party with his friends.", "vi": "Anh ấy sẽ đến bữa tiệc cùng bạn bè."}, {"en": "Happy New Year to everyone!", "vi": "Chúc mừng năm mới tới tất cả mọi người!"}],
        "speaking": [{"en": "What will you do for New Year?", "vi": "Bạn sẽ làm gì vào dịp năm mới?"}, {"en": "I'll visit my grandparents.", "vi": "Tôi sẽ đi thăm ông bà."}, {"en": "Will there be fireworks?", "vi": "Sẽ có pháo hoa chứ?"}, {"en": "Yes, at midnight.", "vi": "Có, vào lúc nửa đêm."}, {"en": "I love festivals.", "vi": "Tôi yêu các lễ hội."}, {"en": "Me too, they are fun.", "vi": "Tôi cũng vậy, chúng rất vui."}, {"en": "Are you going to the party?", "vi": "Bạn có đi dự tiệc không?"}, {"en": "Yes, I'll be there.", "vi": "Có, tôi sẽ ở đó."}, {"en": "Don't forget the gift!", "vi": "Đừng quên quà đấy nhé!"}, {"en": "I won't.", "vi": "Tôi sẽ không quên đâu."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I will _____ the New Year.", "answer": "celebrate", "hint": "ăn mừng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Watch _____.", "answer": "fireworks", "hint": "pháo hoa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go to a _____.", "answer": "party", "hint": "bữa tiệc"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Give a _____.", "answer": "gift", "hint": "món quà"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A street _____.", "answer": "parade", "hint": "diễu hành"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Traditional _____.", "answer": "festival", "hint": "lễ hội"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Happy _____ Year!", "answer": "New", "hint": "Năm (mới)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Enjoy the _____.", "answer": "holiday", "hint": "ngày nghỉ lễ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Follow _____.", "answer": "tradition", "hint": "truyền thống"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Play loud _____.", "answer": "music", "hint": "âm nhạc"}],
        "quizzes": [{"question": "'Celebrate' nghĩa là gì?", "options": ["Kỷ niệm", "Học tập", "Làm việc", "Nghỉ ngơi"], "correct": 0}, {"question": "I _____ give you a gift.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "They _____ stay at home.", "options": ["won't", "will", "is", "does"], "correct": 0}, {"question": "Will you _____ the parade?", "options": ["watch", "watches", "watching", "watched"], "correct": 0}, {"question": "The party _____ start at 8.", "options": ["will", "is", "are", "do"], "correct": 0}, {"question": "'Fireworks' nghĩa là gì?", "options": ["Pháo hoa", "Lửa", "Nước", "Gió"], "correct": 0}, {"question": "A _____ festival.", "options": ["traditional", "tradition", "traditions", "traditionally"], "correct": 0}, {"question": "Give _____ gift.", "options": ["a", "an", "the", "some"], "correct": 0}, {"question": "Happy _____ Year!", "options": ["New", "Old", "Good", "Fine"], "correct": 0}, {"question": "We _____ have fun.", "options": ["will", "is", "am", "are"], "correct": 0}]
    }
}

for d in week4_data:
    update_lesson(d, week4_data[d])
print("Week 4 Batch 1 updated.")
