import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 2:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]
        lesson["tense"]["rules"][1]["examples"] = data["grammar_negative"]
    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week2_data = {
    12: { # Health
        "grammar_affirmative": [{"en": "I am feeling much better now.", "vi": "Bây giờ tôi đang cảm thấy tốt hơn nhiều."}, {"en": "She is recovering from a cold.", "vi": "Cô ấy đang hồi phục sau trận cảm lạnh."}, {"en": "They are exercising to stay fit.", "vi": "Họ đang tập thể dục để giữ dáng."}],
        "grammar_negative": [{"en": "I am not feeling well today.", "vi": "Hôm nay tôi cảm thấy không khỏe."}, {"en": "He is not sleeping enough.", "vi": "Anh ấy đang không ngủ đủ giấc."}, {"en": "We are not eating junk food.", "vi": "Chúng tôi không ăn đồ ăn vặt."}],
        "vocabulary": [
            {"word": "Health", "phonetic": "/helθ/", "meaning": "Sức khỏe", "example": "Health is important.", "exampleVi": "Sức khỏe là quan trọng."},
            {"word": "Body", "phonetic": "/ˈbɑː.di/", "meaning": "Cơ thể", "example": "My body is tired.", "exampleVi": "Cơ thể tôi mệt mỏi."},
            {"word": "Head", "phonetic": "/hed/", "meaning": "Đầu", "example": "I have a headache.", "exampleVi": "Tôi bị đau đầu."},
            {"word": "Eye", "phonetic": "/aɪ/", "meaning": "Mắt", "example": "Close your eyes.", "exampleVi": "Hãy nhắm mắt lại."},
            {"word": "Hand", "phonetic": "/hænd/", "meaning": "Bàn tay", "example": "Wash your hands.", "exampleVi": "Hãy rửa tay của bạn."},
            {"word": "Foot", "phonetic": "/fʊt/", "meaning": "Bàn chân", "example": "My feet are sore.", "exampleVi": "Bàn chân tôi bị đau."},
            {"word": "Cold", "phonetic": "/koʊld/", "meaning": "Cảm lạnh", "example": "I have a cold.", "exampleVi": "Tôi bị cảm lạnh."},
            {"word": "Doctor", "phonetic": "/ˈdɑːk.tɚ/", "meaning": "Bác sĩ", "example": "Go to the doctor.", "exampleVi": "Đi bác sĩ."},
            {"word": "Medicine", "phonetic": "/ˈmed.ɪ.sən/", "meaning": "Thuốc", "example": "Take your medicine.", "exampleVi": "Hãy uống thuốc của bạn."},
            {"word": "Healthy", "phonetic": "/ˈhel.θi/", "meaning": "Khỏe mạnh", "example": "Eat healthy food.", "exampleVi": "Ăn thức ăn lành mạnh."}
        ],
        "listening": [{"en": "I am feeling a bit sick today.", "vi": "Hôm nay tôi cảm thấy hơi ốm."}, {"en": "What is wrong with you?", "vi": "Bạn bị làm sao vậy?"}, {"en": "I have a terrible headache.", "vi": "Tôi bị đau đầu khủng khiếp."}, {"en": "You should go to the doctor.", "vi": "Bạn nên đi bác sĩ."}, {"en": "She is taking medicine now.", "vi": "Cô ấy hiện đang uống thuốc."}, {"en": "Is he feeling better?", "vi": "Anh ấy có đang cảm thấy tốt hơn không?"}, {"en": "Wash your hands before eating.", "vi": "Hãy rửa tay trước khi ăn."}, {"en": "Exercise is good for your body.", "vi": "Tập thể dục tốt cho cơ thể của bạn."}, {"en": "Drink plenty of water.", "vi": "Hãy uống nhiều nước."}, {"en": "She is resting in bed.", "vi": "Cô ấy đang nghỉ ngơi trên giường."}],
        "speaking": [{"en": "How do you feel?", "vi": "Bạn cảm thấy thế nào?"}, {"en": "I feel tired.", "vi": "Tôi cảm thấy mệt."}, {"en": "Do you have a fever?", "vi": "Bạn có bị sốt không?"}, {"en": "Yes, I think so.", "vi": "Có, tôi nghĩ vậy."}, {"en": "I have a sore throat.", "vi": "Tôi bị đau họng."}, {"en": "Drink some warm tea.", "vi": "Hãy uống một chút trà ấm."}, {"en": "I am allergic to cats.", "vi": "Tôi bị dị ứng với mèo."}, {"en": "Are you taking any medicine?", "vi": "Bạn có đang uống thuốc gì không?"}, {"en": "Get well soon!", "vi": "Chúc mau khỏe nhé!"}, {"en": "Thank you.", "vi": "Cảm ơn bạn."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I am _____ better now.", "answer": "feeling", "hint": "đang cảm thấy"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go to the _____.", "answer": "doctor", "hint": "bác sĩ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Take your _____.", "answer": "medicine", "hint": "thuốc"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I have a _____.", "answer": "headache", "hint": "đau đầu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Wash your _____.", "answer": "hands", "hint": "bàn tay (số nhiều)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Eat _____ food.", "answer": "healthy", "hint": "lành mạnh"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "My _____ is tired.", "answer": "body", "hint": "cơ thể"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Close your _____.", "answer": "eyes", "hint": "mắt (số nhiều)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I have a _____.", "answer": "cold", "hint": "cảm lạnh"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Health is _____.", "answer": "important", "hint": "quan trọng"}],
        "quizzes": [{"question": "'Medicine' nghĩa là gì?", "options": ["Thức ăn", "Nước uống", "Thuốc", "Quần áo"], "correct": 2}, {"question": "I am _____ better.", "options": ["feel", "feeling", "feels", "felt"], "correct": 1}, {"question": "She _____ feeling well.", "options": ["is not", "am not", "are not", "do not"], "correct": 0}, {"question": "You _____ go to the doctor.", "options": ["should", "shouldn't", "is", "are"], "correct": 0}, {"question": "I have _____ headache.", "options": ["a", "an", "the", "some"], "correct": 0}, {"question": "Wash _____ hands.", "options": ["you", "your", "yours", "me"], "correct": 1}, {"question": "'Healthy' nghĩa là gì?", "options": ["Ốm", "Yếu", "Khỏe mạnh", "Mệt"], "correct": 2}, {"question": "How _____ you feel?", "options": ["do", "does", "is", "are"], "correct": 0}, {"question": "Get _____ soon!", "options": ["well", "good", "better", "best"], "correct": 0}, {"question": "My feet _____ sore.", "options": ["is", "am", "are", "be"], "correct": 2}]
    },
    13: { # Sports
        "grammar_affirmative": [{"en": "He is playing football.", "vi": "Anh ấy đang chơi bóng đá."}, {"en": "They are running a race.", "vi": "Họ đang chạy đua."}, {"en": "We are winning the game.", "vi": "Chúng tôi đang thắng trận đấu."}],
        "grammar_negative": [{"en": "I am not playing tennis.", "vi": "Tôi đang không chơi tennis."}, {"en": "She is not swimming today.", "vi": "Cô ấy không đang bơi hôm nay."}, {"en": "They are not losing.", "vi": "Họ đang không thua."}],
        "vocabulary": [
            {"word": "Sport", "phonetic": "/spɔːrt/", "meaning": "Thể thao", "example": "I like sports.", "exampleVi": "Tôi thích thể thao."},
            {"word": "Football", "phonetic": "/ˈfʊt.bɑːl/", "meaning": "Bóng đá", "example": "Play football.", "exampleVi": "Chơi bóng đá."},
            {"word": "Tennis", "phonetic": "/ˈten.ɪs/", "meaning": "Tennis/Quần vợt", "example": "Play tennis.", "exampleVi": "Chơi tennis."},
            {"word": "Swimming", "phonetic": "/ˈswɪm.ɪŋ/", "meaning": "Bơi lội", "example": "I like swimming.", "exampleVi": "Tôi thích bơi."},
            {"word": "Running", "phonetic": "/ˈrʌn.ɪŋ/", "meaning": "Chạy bộ", "example": "Running is good.", "exampleVi": "Chạy bộ rất tốt."},
            {"word": "Team", "phonetic": "/tiːm/", "meaning": "Đội", "example": "My team is great.", "exampleVi": "Đội của tôi rất tuyệt."},
            {"word": "Game", "phonetic": "/ɡeɪm/", "meaning": "Trò chơi/Trận đấu", "example": "A fun game.", "exampleVi": "Một trò chơi vui."},
            {"word": "Ball", "phonetic": "/bɑːl/", "meaning": "Quả bóng", "example": "Kick the ball.", "exampleVi": "Đá quả bóng."},
            {"word": "Win", "phonetic": "/wɪn/", "meaning": "Thắng", "example": "We want to win.", "exampleVi": "Chúng tôi muốn thắng."},
            {"word": "Lose", "phonetic": "/luːz/", "meaning": "Thua", "example": "Don't lose.", "exampleVi": "Đừng để thua."}
        ],
        "listening": [{"en": "Are you playing football now?", "vi": "Bây giờ bạn có đang chơi bóng đá không?"}, {"en": "The team is practicing hard.", "vi": "Đội đang luyện tập chăm chỉ."}, {"en": "She is winning the tennis match.", "vi": "Cô ấy đang thắng trận tennis."}, {"en": "They are running in the park.", "vi": "Họ đang chạy bộ trong công viên."}, {"en": "I am not swimming because it's cold.", "vi": "Tôi không bơi vì trời lạnh."}, {"en": "Who is winning the game?", "vi": "Ai đang thắng trận đấu?"}, {"en": "Kick the ball to me!", "vi": "Đá quả bóng cho tôi!"}, {"en": "We are losing the match.", "vi": "Chúng tôi đang thua trận."}, {"en": "He is a great sports player.", "vi": "Anh ấy là một vận động viên tuyệt vời."}, {"en": "Are they playing together?", "vi": "Họ đang chơi cùng nhau à?"}],
        "speaking": [{"en": "What is your favorite sport?", "vi": "Môn thể thao yêu thích của bạn là gì?"}, {"en": "I like football.", "vi": "Tôi thích bóng đá."}, {"en": "Are you playing today?", "vi": "Hôm nay bạn có chơi không?"}, {"en": "No, I am tired.", "vi": "Không, tôi mệt rồi."}, {"en": "Let's go running.", "vi": "Chúng ta đi chạy bộ đi."}, {"en": "I love swimming in the sea.", "vi": "Tôi yêu bơi lội dưới biển."}, {"en": "Who is your favorite team?", "vi": "Đội bóng yêu thích của bạn là gì?"}, {"en": "I like Manchester United.", "vi": "Tôi thích Manchester United."}, {"en": "We are winning!", "vi": "Chúng ta đang thắng!"}, {"en": "Keep going!", "vi": "Tiếp tục cố gắng nào!"}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He is _____ football.", "answer": "playing", "hint": "đang chơi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I like _____.", "answer": "swimming", "hint": "bơi lội"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "We are _____ the game.", "answer": "winning", "hint": "đang thắng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Kick the _____.", "answer": "ball", "hint": "quả bóng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "My _____ is great.", "answer": "team", "hint": "đội"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "They are _____.", "answer": "running", "hint": "đang chạy"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I play _____.", "answer": "tennis", "hint": "tennis"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Don't _____.", "answer": "lose", "hint": "thua"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A fun _____.", "answer": "game", "hint": "trò chơi/trận đấu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I like _____.", "answer": "sports", "hint": "thể thao"}],
        "quizzes": [{"question": "'Football' là môn gì?", "options": ["Bóng đá", "Bóng chuyền", "Bóng rổ", "Bóng chày"], "correct": 0}, {"question": "They are _____ now.", "options": ["run", "running", "runs", "ran"], "correct": 1}, {"question": "We _____ winning.", "options": ["is", "am", "are", "be"], "correct": 2}, {"question": "Is she _____ tennis?", "options": ["play", "playing", "plays", "played"], "correct": 1}, {"question": "I am _____ losing.", "options": ["not", "no", "don't", "doesn't"], "correct": 0}, {"question": "'Win' nghĩa là gì?", "options": ["Thắng", "Thua", "Hòa", "Chơi"], "correct": 0}, {"question": "Kick the _____.", "options": ["ball", "game", "team", "sport"], "correct": 0}, {"question": "Are _____ playing together?", "options": ["you", "your", "yours", "me"], "correct": 0}, {"question": "My favorite _____ is swimming.", "options": ["sport", "game", "team", "ball"], "correct": 0}, {"question": "He _____ playing well.", "options": ["is", "am", "are", "be"], "correct": 0}]
    },
    14: { # Music & Movies
        "grammar_affirmative": [{"en": "I am listening to music.", "vi": "Tôi đang nghe nhạc."}, {"en": "She is watching a movie.", "vi": "Cô ấy đang xem một bộ phim."}, {"en": "They are singing a song.", "vi": "Họ đang hát một bài hát."}],
        "grammar_negative": [{"en": "I am not watching TV.", "vi": "Tôi không đang xem tivi."}, {"en": "He is not listening to us.", "vi": "Anh ấy không đang nghe chúng tôi."}, {"en": "We are not going to the cinema.", "vi": "Chúng tôi không đi xem phim (rạp)."}],
        "vocabulary": [
            {"word": "Music", "phonetic": "/ˈmjuː.zɪk/", "meaning": "Âm nhạc", "example": "Listen to music.", "exampleVi": "Nghe nhạc."},
            {"word": "Movie", "phonetic": "/ˈmuː.vi/", "meaning": "Phim", "example": "Watch a movie.", "exampleVi": "Xem phim."},
            {"word": "Song", "phonetic": "/sɔːŋ/", "meaning": "Bài hát", "example": "Sing a song.", "exampleVi": "Hát một bài hát."},
            {"word": "Singer", "phonetic": "/ˈsɪŋ.ɚ/", "meaning": "Ca sĩ", "example": "She is a singer.", "exampleVi": "Cô ấy là ca sĩ."},
            {"word": "Actor", "phonetic": "/ˈæk.tɚ/", "meaning": "Diễn viên", "example": "He is an actor.", "exampleVi": "Anh ấy là diễn viên."},
            {"word": "Cinema", "phonetic": "/ˈsɪn.ə.mə/", "meaning": "Rạp chiếu phim", "example": "Go to the cinema.", "exampleVi": "Đi xem phim."},
            {"word": "Piano", "phonetic": "/piˈæn.oʊ/", "meaning": "Đàn piano", "example": "Play the piano.", "exampleVi": "Chơi đàn piano."},
            {"word": "Guitar", "phonetic": "/ɡɪˈtɑːr/", "meaning": "Đàn guitar", "example": "Play the guitar.", "exampleVi": "Chơi đàn guitar."},
            {"word": "Listen", "phonetic": "/ˈlɪs.ən/", "meaning": "Nghe", "example": "Listen to me.", "exampleVi": "Hãy nghe tôi."},
            {"word": "Watch", "phonetic": "/wɑːtʃ/", "meaning": "Xem", "example": "Watch TV.", "exampleVi": "Xem tivi."}
        ],
        "listening": [{"en": "What are you listening to?", "vi": "Bạn đang nghe gì vậy?"}, {"en": "I am listening to a new song.", "vi": "Tôi đang nghe một bài hát mới."}, {"en": "She is watching a romantic movie.", "vi": "Cô ấy đang xem một bộ phim lãng mạn."}, {"en": "Are they going to the cinema tonight?", "vi": "Họ có đi xem phim tối nay không?"}, {"en": "The singer is performing on stage.", "vi": "Ca sĩ đang biểu diễn trên sân khấu."}, {"en": "He is playing the guitar beautifully.", "vi": "Anh ấy đang chơi guitar rất hay."}, {"en": "I am not watching horror movies.", "vi": "Tôi không đang xem phim kinh dị."}, {"en": "Is she playing the piano?", "vi": "Cô ấy có đang chơi piano không?"}, {"en": "We are singing together.", "vi": "Chúng tôi đang hát cùng nhau."}, {"en": "The actor is very famous.", "vi": "Diễn viên đó rất nổi tiếng."}],
        "speaking": [{"en": "Do you like music?", "vi": "Bạn có thích âm nhạc không?"}, {"en": "Yes, I love pop music.", "vi": "Có, tôi yêu nhạc pop."}, {"en": "Who is your favorite singer?", "vi": "Ca sĩ yêu thích của bạn là ai?"}, {"en": "I like Taylor Swift.", "vi": "Tôi thích Taylor Swift."}, {"en": "What movie are you watching?", "vi": "Bạn đang xem phim gì thế?"}, {"en": "I am watching an action movie.", "vi": "Tôi đang xem một bộ phim hành động."}, {"en": "Do you play any instruments?", "vi": "Bạn có chơi nhạc cụ nào không?"}, {"en": "I play the guitar.", "vi": "Tôi chơi guitar."}, {"en": "Let's go to the cinema.", "vi": "Chúng ta hãy đi rạp chiếu phim đi."}, {"en": "Great idea!", "vi": "Ý kiến hay đấy!"}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I am _____ to music.", "answer": "listening", "hint": "đang nghe"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She is _____ a movie.", "answer": "watching", "hint": "đang xem"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "They are _____ a song.", "answer": "singing", "hint": "đang hát"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She is a famous _____.", "answer": "singer", "hint": "ca sĩ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He is an _____.", "answer": "actor", "hint": "diễn viên"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go to the _____.", "answer": "cinema", "hint": "rạp chiếu phim"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I play the _____.", "answer": "guitar", "hint": "đàn guitar"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She plays the _____.", "answer": "piano", "hint": "đàn piano"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Listen to the _____.", "answer": "music", "hint": "âm nhạc"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Watch a _____.", "answer": "movie", "hint": "bộ phim"}],
        "quizzes": [{"question": "'Movie' nghĩa là gì?", "options": ["Bài hát", "Bộ phim", "Vở kịch", "Quyển sách"], "correct": 1}, {"question": "I am listening _____ music.", "options": ["to", "at", "on", "in"], "correct": 0}, {"question": "She _____ watching a movie.", "options": ["is", "am", "are", "be"], "correct": 0}, {"question": "They are _____ a song.", "options": ["sing", "singing", "sings", "sang"], "correct": 1}, {"question": "Are you _____ the piano?", "options": ["play", "playing", "plays", "played"], "correct": 1}, {"question": "I am _____ watching TV.", "options": ["not", "no", "don't", "doesn't"], "correct": 0}, {"question": "'Singer' nghĩa là gì?", "options": ["Diễn viên", "Ca sĩ", "Nhạc sĩ", "Họa sĩ"], "correct": 1}, {"question": "Go to the _____.", "options": ["cinema", "theatre", "museum", "park"], "correct": 0}, {"question": "He _____ playing the guitar.", "options": ["is", "am", "are", "be"], "correct": 0}, {"question": "A famous _____.", "options": ["actor", "actress", "action", "acting"], "correct": 0}]
    }
}

for d in week2_data:
    update_lesson(d, week2_data[d])
print("Week 2 Batch 3 updated.")
