import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    
    # Review lessons might have different tense structure
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 1:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]

    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week5_data = {
    29: { # Review Part 1
        "grammar_affirmative": [{"en": "I learn English every day.", "vi": "Tôi học tiếng Anh mỗi ngày."}, {"en": "Yesterday I learned new words.", "vi": "Hôm qua tôi đã học những từ mới."}, {"en": "Tomorrow I will practice speaking.", "vi": "Ngày mai tôi sẽ luyện nói."}],
        "vocabulary": [
            {"word": "Review", "phonetic": "/rɪˈvjuː/", "meaning": "Ôn tập", "example": "Review your lessons.", "exampleVi": "Ôn lại các bài học của bạn."},
            {"word": "Practice", "phonetic": "/ˈpræk.tɪs/", "meaning": "Luyện tập", "example": "Practice makes perfect.", "exampleVi": "Luyện tập tạo nên sự hoàn hảo."},
            {"word": "Remember", "phonetic": "/rɪˈmem.bɚ/", "meaning": "Ghi nhớ", "example": "Remember my name.", "exampleVi": "Hãy nhớ tên tôi."},
            {"word": "Understand", "phonetic": "/ˌʌn.dɚˈstænd/", "meaning": "Hiểu", "example": "I understand.", "exampleVi": "Tôi hiểu."},
            {"word": "Knowledge", "phonetic": "/ˈnɑː.lɪdʒ/", "meaning": "Kiến thức", "example": "Gain knowledge.", "exampleVi": "Tiếp thu kiến thức."},
            {"word": "Improve", "phonetic": "/ɪmˈpruːv/", "meaning": "Cải thiện", "example": "Improve your skills.", "exampleVi": "Cải thiện kỹ năng của bạn."},
            {"word": "Progress", "phonetic": "/ˈprɑː.ɡres/", "meaning": "Sự tiến bộ", "example": "Make progress.", "exampleVi": "Có sự tiến bộ."},
            {"word": "Goal", "phonetic": "/ɡoʊl/", "meaning": "Mục tiêu", "example": "Achieve your goal.", "exampleVi": "Đạt được mục tiêu của bạn."},
            {"word": "Success", "phonetic": "/səkˈses/", "meaning": "Thành công", "example": "Success is hard work.", "exampleVi": "Thành công là nhờ làm việc chăm chỉ."},
            {"word": "Confidence", "phonetic": "/ˈkɑːn.fə.dəns/", "meaning": "Sự tự tin", "example": "Speak with confidence.", "exampleVi": "Nói chuyện với sự tự tin."}
        ],
        "listening": [{"en": "We have finished four weeks of learning.", "vi": "Chúng ta đã hoàn thành bốn tuần học."}, {"en": "It is time to review what we learned.", "vi": "Đã đến lúc ôn lại những gì chúng ta đã học."}, {"en": "I practice English for thirty minutes every day.", "vi": "Tôi luyện tập tiếng Anh 30 phút mỗi ngày."}, {"en": "Did you remember all the vocabulary?", "vi": "Bạn có nhớ hết các từ vựng không?"}, {"en": "I understand the grammar rules now.", "vi": "Bây giờ tôi đã hiểu các quy tắc ngữ pháp."}, {"en": "My speaking skills are improving.", "vi": "Kỹ năng nói của tôi đang được cải thiện."}, {"en": "I made a lot of progress this month.", "vi": "Tôi đã có nhiều tiến bộ trong tháng này."}, {"en": "Always set a clear goal for your study.", "vi": "Luôn đặt mục tiêu rõ ràng cho việc học của bạn."}, {"en": "Don't be afraid to make mistakes.", "vi": "Đừng sợ mắc lỗi."}, {"en": "Confidence is the key to success.", "vi": "Tự tin là chìa khóa của thành công."}],
        "speaking": [{"en": "How was your learning process?", "vi": "Quá trình học tập của bạn thế nào?"}, {"en": "It was very interesting.", "vi": "Nó đã rất thú vị."}, {"en": "What did you like the most?", "vi": "Bạn thích điều gì nhất?"}, {"en": "I liked the topics about daily life.", "vi": "Tôi thích các chủ đề về cuộc sống hàng ngày."}, {"en": "Are you confident now?", "vi": "Bây giờ bạn đã tự tin chưa?"}, {"en": "Yes, more than before.", "vi": "Rồi, tự tin hơn trước."}, {"en": "I will continue to practice.", "vi": "Tôi sẽ tiếp tục luyện tập."}, {"en": "That's great to hear!", "vi": "Thật tuyệt khi nghe vậy!"}, {"en": "Keep up the good work.", "vi": "Hãy tiếp tục phát huy nhé."}, {"en": "Thank you for your help.", "vi": "Cảm ơn vì sự giúp đỡ của bạn."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ English every day.", "answer": "learn", "hint": "học"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Yesterday I _____ new words.", "answer": "learned", "hint": "đã học"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ makes perfect.", "answer": "Practice", "hint": "Luyện tập"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ the rules.", "answer": "understand", "hint": "hiểu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Improve your _____.", "answer": "skills", "hint": "kỹ năng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Make _____.", "answer": "progress", "hint": "sự tiến bộ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Achieve your _____.", "answer": "goal", "hint": "mục tiêu"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Speak with _____.", "answer": "confidence", "hint": "sự tự tin"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Don't _____ your dreams.", "answer": "forget", "hint": "quên"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ what you learned.", "answer": "Review", "hint": "Ôn tập"}],
        "quizzes": [{"question": "'Understand' nghĩa là gì?", "options": ["Hiểu", "Quên", "Học", "Nói"], "correct": 0}, {"question": "I _____ English for a month now.", "options": ["learn", "learned", "have learned", "am learning"], "correct": 2}, {"question": "Practice _____ perfect.", "options": ["make", "makes", "making", "made"], "correct": 1}, {"question": "I _____ my goal last week.", "options": ["achieve", "achieved", "achieves", "achieving"], "correct": 1}, {"question": "Will you _____ practicing?", "options": ["keep", "keeps", "keeping", "kept"], "correct": 0}, {"question": "'Confidence' nghĩa là gì?", "options": ["Sự tự tin", "Sự lo lắng", "Sự sợ hãi", "Sự buồn bã"], "correct": 0}, {"question": "My skills _____ improving.", "options": ["is", "am", "are", "be"], "correct": 2}, {"question": "I _____ progress every day.", "options": ["make", "makes", "making", "made"], "correct": 0}, {"question": "Don't _____ mistakes.", "options": ["be afraid of", "afraid of", "afraid", "be afraid"], "correct": 0}, {"question": "Success _____ hard work.", "options": ["is", "am", "are", "do"], "correct": 0}]
    },
    30: { # Review Part 2
        "grammar_affirmative": [{"en": "I can speak English now.", "vi": "Bây giờ tôi có thể nói tiếng Anh."}, {"en": "I will study more next month.", "vi": "Tôi sẽ học nhiều hơn vào tháng tới."}, {"en": "We finished the course.", "vi": "Chúng ta đã hoàn thành khóa học."}],
        "vocabulary": [
            {"word": "Finish", "phonetic": "/ˈfɪn.ɪʃ/", "meaning": "Hoàn thành", "example": "Finish the task.", "exampleVi": "Hoàn thành nhiệm vụ."},
            {"word": "Course", "phonetic": "/kɔːrs/", "meaning": "Khóa học", "example": "An English course.", "exampleVi": "Một khóa học tiếng Anh."},
            {"word": "Speak", "phonetic": "/spiːk/", "meaning": "Nói", "example": "Speak slowly.", "exampleVi": "Nói chậm thôi."},
            {"word": "Write", "phonetic": "/raɪt/", "meaning": "Viết", "example": "Write a story.", "exampleVi": "Viết một câu chuyện."},
            {"word": "Read", "phonetic": "/riːd/", "meaning": "Đọc", "example": "Read a news.", "exampleVi": "Đọc tin tức."},
            {"word": "Listen", "phonetic": "/ˈlɪs.ən/", "meaning": "Nghe", "example": "Listen carefully.", "exampleVi": "Lắng nghe cẩn thận."},
            {"word": "Communication", "phonetic": "/kəˌmjuː.nəˈkeɪ.ʃən/", "meaning": "Giao tiếp", "example": "Effective communication.", "exampleVi": "Giao tiếp hiệu quả."},
            {"word": "Fluent", "phonetic": "/ˈfluː.ənt/", "meaning": "Trôi chảy", "example": "Speak fluent English.", "exampleVi": "Nói tiếng Anh trôi chảy."},
            {"word": "Motivation", "phonetic": "/ˌmoʊ.t̬əˈveɪ.ʃən/", "meaning": "Động lực", "example": "Keep your motivation.", "exampleVi": "Giữ vững động lực."},
            {"word": "Result", "phonetic": "/rɪˈzʌlt/", "meaning": "Kết quả", "example": "Great results.", "exampleVi": "Kết quả tuyệt vời."}
        ],
        "listening": [{"en": "Congratulations on finishing the 30-day course!", "vi": "Chúc mừng bạn đã hoàn thành khóa học 30 ngày!"}, {"en": "You can speak English with more confidence now.", "vi": "Bây giờ bạn có thể nói tiếng Anh tự tin hơn."}, {"en": "I will continue to improve my communication skills.", "vi": "Tôi sẽ tiếp tục cải thiện kỹ năng giao tiếp của mình."}, {"en": "Writing and reading are also very important.", "vi": "Viết và đọc cũng rất quan trọng."}, {"en": "Keep listening to English every day.", "vi": "Hãy tiếp tục nghe tiếng Anh mỗi ngày."}, {"en": "The results of your hard work are amazing.", "vi": "Kết quả của sự chăm chỉ của bạn thật đáng kinh ngạc."}, {"en": "Don't lose your motivation to learn new things.", "vi": "Đừng làm mất động lực học những điều mới."}, {"en": "One day you will be fluent in English.", "vi": "Một ngày nào đó bạn sẽ thông thạo tiếng Anh."}, {"en": "We learned a lot about different topics.", "vi": "Chúng ta đã học được nhiều về các chủ đề khác nhau."}, {"en": "Thank you for being a great student!", "vi": "Cảm ơn bạn đã là một học sinh tuyệt vời!"}],
        "speaking": [{"en": "I finished the course today!", "vi": "Hôm nay tôi đã hoàn thành khóa học!"}, {"en": "Well done!", "vi": "Giỏi lắm!"}, {"en": "What will you do next?", "vi": "Bạn sẽ làm gì tiếp theo?"}, {"en": "I'll take an advanced course.", "vi": "Tôi sẽ học một khóa nâng cao."}, {"en": "Can you speak fluently?", "vi": "Bạn có thể nói trôi chảy không?"}, {"en": "Not yet, but I'm trying.", "vi": "Chưa, nhưng tôi đang cố gắng."}, {"en": "I love communicating in English.", "vi": "Tôi yêu việc giao tiếp bằng tiếng Anh."}, {"en": "It's a useful skill.", "vi": "Đó là một kỹ năng hữu ích."}, {"en": "Let's keep in touch.", "vi": "Hãy giữ liên lạc nhé."}, {"en": "Definitely, see you soon!", "vi": "Chắc chắn rồi, hẹn sớm gặp lại!"}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ the course.", "answer": "finished", "hint": "đã hoàn thành"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I can _____ English.", "answer": "speak", "hint": "nói"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Effective _____.", "answer": "communication", "hint": "giao tiếp"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Keep your _____.", "answer": "motivation", "hint": "động lực"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Great _____.", "answer": "results", "hint": "kết quả"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Speak _____ English.", "answer": "fluent", "hint": "trôi chảy"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Listen _____.", "answer": "carefully", "hint": "cẩn thận"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Write a _____.", "answer": "story", "hint": "câu chuyện"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Read the _____.", "answer": "news", "hint": "tin tức"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "_____ on your success!", "answer": "Congratulations", "hint": "Chúc mừng"}],
        "quizzes": [{"question": "'Fluent' nghĩa là gì?", "options": ["Trôi chảy", "Ngắc ngứ", "Chậm chạp", "Nhanh"], "correct": 0}, {"question": "I _____ the course today.", "options": ["finish", "finished", "finishes", "finishing"], "correct": 1}, {"question": "You _____ speak well now.", "options": ["can", "can't", "is", "are"], "correct": 0}, {"question": "Keep _____ to English.", "options": ["listen", "listening", "listened", "listens"], "correct": 1}, {"question": "We _____ a lot of things.", "options": ["learn", "learned", "learns", "learning"], "correct": 1}, {"question": "'Motivation' nghĩa là gì?", "options": ["Động lực", "Sức mạnh", "Kỹ năng", "Kiến thức"], "correct": 0}, {"question": "The results _____ amazing.", "options": ["is", "am", "are", "be"], "correct": 2}, {"question": "I _____ continue to study.", "options": ["will", "won't", "am", "do"], "correct": 0}, {"question": "Speak _____ confidence.", "options": ["with", "by", "at", "on"], "correct": 0}, {"question": "_____ on your success!", "options": ["Congratulations", "Congratulate", "Congratulating", "Congratulated"], "correct": 0}]
    }
}

for d in week5_data:
    update_lesson(d, week5_data[d])
print("Week 5 updated.")
