import json
import os

data_dir = r"d:\WEBHOCTA\webhoctienganhmoingay\data\lessons"

def update_lesson(day, data):
    file_path = os.path.join(data_dir, f"day{day}.json")
    if not os.path.exists(file_path): return
    with open(file_path, 'r', encoding='utf-8') as f:
        lesson = json.load(f)
    if "tense" in lesson and "rules" in lesson["tense"] and len(lesson["tense"]["rules"]) >= 2:
        lesson["tense"]["rules"][0]["examples"] = data["grammar_affirmative"]
        lesson["tense"]["rules"][1]["examples"] = data["grammar_negative"]
    lesson["vocabulary"] = [{"id": f"v{day}_{i+1}", **v} for i, v in enumerate(data["vocabulary"])]
    lesson["listening"] = [{"id": f"l{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["listening"])]
    lesson["speaking"] = [{"id": f"s{day}_{i+1}", "sentence": s["en"], "sentenceVi": s["vi"]} for i, s in enumerate(data["speaking"])]
    lesson["writing"] = [{"id": f"w{day}_{i+1}", **w} for i, w in enumerate(data["writing"])]
    lesson["quizzes"] = [{"id": f"q{day}_{i+1}", **q} for i, q in enumerate(data["quizzes"])]
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(lesson, f, ensure_ascii=False, indent=2)

week3_data = {
    18: { # Home
        "grammar_affirmative": [{"en": "I cleaned the house.", "vi": "Tôi đã dọn dẹp nhà cửa."}, {"en": "She bought a new sofa.", "vi": "Cô ấy đã mua một chiếc ghế sofa mới."}, {"en": "We moved to a new flat.", "vi": "Chúng tôi đã chuyển đến một căn hộ mới."}],
        "grammar_negative": [{"en": "I didn't paint the walls.", "vi": "Tôi đã không sơn tường."}, {"en": "He didn't fix the chair.", "vi": "Anh ấy đã không sửa cái ghế."}, {"en": "They didn't sell the house.", "vi": "Họ đã không bán ngôi nhà."}],
        "vocabulary": [
            {"word": "Home", "phonetic": "/hoʊm/", "meaning": "Nhà/Tổ ấm", "example": "Stay at home.", "exampleVi": "Ở nhà."},
            {"word": "House", "phonetic": "/haʊs/", "meaning": "Ngôi nhà", "example": "A big house.", "exampleVi": "Một ngôi nhà lớn."},
            {"word": "Sofa", "phonetic": "/ˈsoʊ.fə/", "meaning": "Ghế sofa", "example": "Sit on the sofa.", "exampleVi": "Ngồi trên sofa."},
            {"word": "Table", "phonetic": "/ˈteɪ.bəl/", "meaning": "Cái bàn", "example": "On the table.", "exampleVi": "Trên bàn."},
            {"word": "Chair", "phonetic": "/tʃer/", "meaning": "Cái ghế", "example": "A wooden chair.", "exampleVi": "Một cái ghế gỗ."},
            {"word": "Bed", "phonetic": "/bed/", "meaning": "Cái giường", "example": "Go to bed.", "exampleVi": "Đi ngủ."},
            {"word": "Kitchen", "phonetic": "/ˈkɪtʃ.ən/", "meaning": "Nhà bếp", "example": "Cook in the kitchen.", "exampleVi": "Nấu ăn trong bếp."},
            {"word": "Door", "phonetic": "/dɔːr/", "meaning": "Cánh cửa", "example": "Open the door.", "exampleVi": "Mở cửa."},
            {"word": "Window", "phonetic": "/ˈwɪn.doʊ/", "meaning": "Cửa sổ", "example": "Look out the window.", "exampleVi": "Nhìn ra ngoài cửa sổ."},
            {"word": "Room", "phonetic": "/ruːm/", "meaning": "Căn phòng", "example": "A clean room.", "exampleVi": "Một căn phòng sạch sẽ."}
        ],
        "listening": [{"en": "I stayed at home last weekend.", "vi": "Tôi đã ở nhà vào cuối tuần trước."}, {"en": "She cleaned her room yesterday.", "vi": "Hôm qua cô ấy đã dọn dẹp phòng của mình."}, {"en": "We bought some new furniture.", "vi": "Chúng tôi đã mua một số nội thất mới."}, {"en": "He fixed the broken window.", "vi": "Anh ấy đã sửa cái cửa sổ bị vỡ."}, {"en": "The cat was sleeping on the sofa.", "vi": "Con mèo đang ngủ trên sofa."}, {"en": "Did you paint the kitchen?", "vi": "Bạn đã sơn nhà bếp chưa?"}, {"en": "I opened the door for her.", "vi": "Tôi đã mở cửa cho cô ấy."}, {"en": "The table was very old.", "vi": "Cái bàn đã rất cũ."}, {"en": "We moved into this house last year.", "vi": "Chúng tôi đã chuyển vào ngôi nhà này năm ngoái."}, {"en": "I didn't see you in the room.", "vi": "Tôi đã không thấy bạn trong phòng."}],
        "speaking": [{"en": "Where do you live?", "vi": "Bạn sống ở đâu?"}, {"en": "I live in a small house.", "vi": "Tôi sống trong một ngôi nhà nhỏ."}, {"en": "How many rooms are there?", "vi": "Có bao nhiêu phòng?"}, {"en": "There are four rooms.", "vi": "Có 4 phòng."}, {"en": "Did you buy a new sofa?", "vi": "Bạn đã mua sofa mới à?"}, {"en": "Yes, it's very comfortable.", "vi": "Vâng, nó rất thoải mái."}, {"en": "I like your kitchen.", "vi": "Tôi thích nhà bếp của bạn."}, {"en": "Thank you, I cleaned it.", "vi": "Cảm ơn, tôi đã dọn dẹp nó rồi."}, {"en": "Close the window, please.", "vi": "Làm ơn đóng cửa sổ lại."}, {"en": "Okay, sure.", "vi": "Được thôi, chắc chắn rồi."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ the house.", "answer": "cleaned", "hint": "đã dọn dẹp"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She _____ a new sofa.", "answer": "bought", "hint": "đã mua"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Sit on the _____.", "answer": "sofa", "hint": "ghế sofa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Open the _____.", "answer": "door", "hint": "cánh cửa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "In the _____.", "answer": "kitchen", "hint": "nhà bếp"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "On the _____.", "answer": "table", "hint": "cái bàn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He _____ the window.", "answer": "fixed", "hint": "đã sửa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A wooden _____.", "answer": "chair", "hint": "cái ghế"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go to _____.", "answer": "bed", "hint": "đi ngủ (bed)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A clean _____.", "answer": "room", "hint": "căn phòng"}],
        "quizzes": [{"question": "'Kitchen' là phòng gì?", "options": ["Khách", "Ngủ", "Bếp", "Tắm"], "correct": 2}, {"question": "I _____ at home yesterday.", "options": ["stay", "stayed", "stays", "staying"], "correct": 1}, {"question": "They _____ not move last week.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "Did you _____ the door?", "options": ["open", "opened", "opens", "opening"], "correct": 0}, {"question": "The chair _____ very expensive.", "options": ["is", "was", "were", "did"], "correct": 1}, {"question": "We _____ a new bed.", "options": ["buy", "bought", "buys", "buying"], "correct": 1}, {"question": "'Window' nghĩa là gì?", "options": ["Cửa sổ", "Cửa chính", "Bức tường", "Trần nhà"], "correct": 0}, {"question": "I _____ see you there.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "She _____ her room.", "options": ["clean", "cleaned", "cleans", "cleaning"], "correct": 1}, {"question": "A big _____.", "options": ["house", "sofa", "table", "chair"], "correct": 0}]
    },
    19: { # Clothes
        "grammar_affirmative": [{"en": "I wore a red dress.", "vi": "Tôi đã mặc một chiếc váy đỏ."}, {"en": "She bought a new hat.", "vi": "Cô ấy đã mua một chiếc mũ mới."}, {"en": "They washed their clothes.", "vi": "Họ đã giặt quần áo của mình."}],
        "grammar_negative": [{"en": "I didn't wear shoes.", "vi": "Tôi đã không đi giày."}, {"en": "He didn't like the shirt.", "vi": "Anh ấy đã không thích chiếc áo sơ mi đó."}, {"en": "We didn't see the suit.", "vi": "Chúng tôi đã không thấy bộ com-lê."}],
        "vocabulary": [
            {"word": "Clothes", "phonetic": "/kloʊðz/", "meaning": "Quần áo", "example": "Wear new clothes.", "exampleVi": "Mặc quần áo mới."},
            {"word": "Shirt", "phonetic": "/ʃɝːt/", "meaning": "Áo sơ mi", "example": "A white shirt.", "exampleVi": "Một chiếc áo trắng."},
            {"word": "Dress", "phonetic": "/dres/", "meaning": "Váy liền", "example": "A beautiful dress.", "exampleVi": "Một chiếc váy đẹp."},
            {"word": "Hat", "phonetic": "/hæt/", "meaning": "Mũ", "example": "Put on your hat.", "exampleVi": "Đội mũ vào."},
            {"word": "Shoes", "phonetic": "/ʃuːz/", "meaning": "Giày", "example": "A pair of shoes.", "exampleVi": "Một đôi giày."},
            {"word": "Pants", "phonetic": "/pænts/", "meaning": "Quần dài", "example": "Blue pants.", "exampleVi": "Quần xanh."},
            {"word": "Skirt", "phonetic": "/skɝːt/", "meaning": "Chân váy", "example": "A short skirt.", "exampleVi": "Một cái chân váy ngắn."},
            {"word": "Coat", "phonetic": "/koʊt/", "meaning": "Áo khoác", "example": "Wear a coat.", "exampleVi": "Mặc áo khoác."},
            {"word": "Sock", "phonetic": "/sɑːk/", "meaning": "Tất/Vớ", "example": "A pair of socks.", "exampleVi": "Một đôi tất."},
            {"word": "Suit", "phonetic": "/suːt/", "meaning": "Bộ com-lê", "example": "He wore a suit.", "exampleVi": "Anh ấy đã mặc com-lê."}
        ],
        "listening": [{"en": "I wore a black suit to the party.", "vi": "Tôi đã mặc một bộ com-lê đen đến bữa tiệc."}, {"en": "She bought a beautiful red dress.", "vi": "Cô ấy đã mua một chiếc váy đỏ rất đẹp."}, {"en": "Did you wash your clothes yesterday?", "vi": "Hôm qua bạn đã giặt quần áo chưa?"}, {"en": "I lost my favorite hat in the park.", "vi": "Tôi đã làm mất chiếc mũ yêu thích trong công viên."}, {"en": "He wore new shoes for the race.", "vi": "Anh ấy đã đi giày mới để chạy đua."}, {"en": "It was cold, so I wore a coat.", "vi": "Trời lạnh nên tôi đã mặc áo khoác."}, {"en": "The pants were too long for me.", "vi": "Cái quần quá dài đối với tôi."}, {"en": "Where did you buy that shirt?", "vi": "Bạn đã mua chiếc áo sơ mi đó ở đâu?"}, {"en": "She wore a white skirt yesterday.", "vi": "Hôm qua cô ấy đã mặc một cái chân váy trắng."}, {"en": "I didn't find my socks this morning.", "vi": "Sáng nay tôi đã không tìm thấy tất của mình."}],
        "speaking": [{"en": "I like your dress.", "vi": "Tôi thích chiếc váy của bạn."}, {"en": "Thank you, I bought it yesterday.", "vi": "Cảm ơn, tôi đã mua nó hôm qua."}, {"en": "What did he wear?", "vi": "Anh ấy đã mặc gì?"}, {"en": "He wore a blue shirt.", "vi": "Anh ấy đã mặc áo sơ mi xanh."}, {"en": "Is it new?", "vi": "Nó mới à?"}, {"en": "Yes, it's new.", "vi": "Vâng, nó mới."}, {"en": "I need new shoes.", "vi": "Tôi cần giày mới."}, {"en": "Me too.", "vi": "Tôi cũng vậy."}, {"en": "That hat is cool.", "vi": "Cái mũ đó ngầu quá."}, {"en": "Thanks!", "vi": "Cảm ơn!"}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ a red dress.", "answer": "wore", "hint": "đã mặc"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She _____ a new hat.", "answer": "bought", "hint": "đã mua"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A white _____.", "answer": "shirt", "hint": "áo sơ mi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A pair of _____.", "answer": "shoes", "hint": "giày"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Put on your _____.", "answer": "hat", "hint": "mũ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I washed my _____.", "answer": "clothes", "hint": "quần áo"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Blue _____.", "answer": "pants", "hint": "quần dài"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Wear a _____.", "answer": "coat", "hint": "áo khoác"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A pair of _____.", "answer": "socks", "hint": "tất/vớ"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He wore a _____.", "answer": "suit", "hint": "bộ com-lê"}],
        "quizzes": [{"question": "'Dress' là loại quần áo gì?", "options": ["Áo sơ mi", "Váy liền", "Quần dài", "Mũ"], "correct": 1}, {"question": "I _____ new shoes yesterday.", "options": ["wear", "wore", "wears", "wearing"], "correct": 1}, {"question": "She _____ not buy the hat.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "Did you _____ your clothes?", "options": ["wash", "washed", "washes", "washing"], "correct": 0}, {"question": "The shirt _____ very expensive.", "options": ["is", "was", "were", "did"], "correct": 1}, {"question": "I _____ my favorite hat.", "options": ["lose", "lost", "loses", "losing"], "correct": 1}, {"question": "'Shoes' nghĩa là gì?", "options": ["Tất", "Giày", "Mũ", "Áo"], "correct": 1}, {"question": "I _____ not find my socks.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "He _____ a black suit.", "options": ["wear", "wore", "wears", "wearing"], "correct": 1}, {"question": "A beautiful _____.", "options": ["dress", "pants", "suit", "shirt"], "correct": 0}]
    },
    20: { # Transportation
        "grammar_affirmative": [{"en": "I took a taxi to the airport.", "vi": "Tôi đã đi taxi đến sân bay."}, {"en": "The bus arrived on time.", "vi": "Xe buýt đã đến đúng giờ."}, {"en": "We flew to New York.", "vi": "Chúng tôi đã bay đến New York."}],
        "grammar_negative": [{"en": "I didn't miss the train.", "vi": "Tôi đã không lỡ chuyến tàu."}, {"en": "He didn't drive the car.", "vi": "Anh ấy đã không lái ô tô."}, {"en": "The plane didn't land yet.", "vi": "Máy bay chưa hạ cánh."}],
        "vocabulary": [
            {"word": "Bus", "phonetic": "/bʌs/", "meaning": "Xe buýt", "example": "Go by bus.", "exampleVi": "Đi bằng xe buýt."},
            {"word": "Train", "phonetic": "/treɪn/", "meaning": "Tàu hỏa", "example": "Take the train.", "exampleVi": "Đi tàu hỏa."},
            {"word": "Taxi", "phonetic": "/ˈtæk.si/", "meaning": "Taxi", "example": "Call a taxi.", "exampleVi": "Gọi taxi."},
            {"word": "Plane", "phonetic": "/pleɪn/", "meaning": "Máy bay", "example": "Fly by plane.", "exampleVi": "Đi bằng máy bay."},
            {"word": "Car", "phonetic": "/kɑːr/", "meaning": "Ô tô", "example": "Drive a car.", "exampleVi": "Lái ô tô."},
            {"word": "Bicycle", "phonetic": "/ˈbaɪ.sə.kəl/", "meaning": "Xe đạp", "example": "Ride a bicycle.", "exampleVi": "Đi xe đạp."},
            {"word": "Motorbike", "phonetic": "/ˈmoʊ.t̬ɚ.baɪk/", "meaning": "Xe máy", "example": "Ride a motorbike.", "exampleVi": "Đi xe máy."},
            {"word": "Ship", "phonetic": "/ʃɪp/", "meaning": "Con tàu thủy", "example": "Travel by ship.", "exampleVi": "Đi bằng tàu thủy."},
            {"word": "Airport", "phonetic": "/ˈer.pɔːrt/", "meaning": "Sân bay", "example": "At the airport.", "exampleVi": "Tại sân bay."},
            {"word": "Station", "phonetic": "/ˈsteɪ.ʃən/", "meaning": "Nhà ga", "example": "Train station.", "exampleVi": "Nhà ga tàu hỏa."}
        ],
        "listening": [{"en": "I went to work by motorbike yesterday.", "vi": "Hôm qua tôi đi làm bằng xe máy."}, {"en": "The train was very crowded.", "vi": "Chuyến tàu đã rất đông đúc."}, {"en": "Did you take a taxi home?", "vi": "Bạn có đi taxi về nhà không?"}, {"en": "The bus arrived ten minutes late.", "vi": "Xe buýt đã đến muộn mười phút."}, {"en": "We flew to Japan last summer.", "vi": "Chúng tôi đã bay đến Nhật Bản mùa hè năm ngoái."}, {"en": "He drove his car to the mountains.", "vi": "Anh ấy đã lái ô tô lên núi."}, {"en": "The ship sailed across the ocean.", "vi": "Con tàu đã vượt đại dương."}, {"en": "I missed the bus this morning.", "vi": "Sáng nay tôi đã lỡ chuyến xe buýt."}, {"en": "The plane landed safely.", "vi": "Máy bay đã hạ cánh an toàn."}, {"en": "Where is the nearest bus station?", "vi": "Trạm xe buýt gần nhất ở đâu?"}],
        "speaking": [{"en": "How did you get here?", "vi": "Bạn đến đây bằng cách nào?"}, {"en": "I came by bus.", "vi": "Tôi đến bằng xe buýt."}, {"en": "Was it fast?", "vi": "Nó có nhanh không?"}, {"en": "Yes, quite fast.", "vi": "Vâng, khá nhanh."}, {"en": "Did you drive your car?", "vi": "Bạn có lái ô tô không?"}, {"en": "No, I took a taxi.", "vi": "Không, tôi đi taxi."}, {"en": "I like riding my bicycle.", "vi": "Tôi thích đi xe đạp."}, {"en": "Me too, it's healthy.", "vi": "Tôi cũng vậy, nó tốt cho sức khỏe."}, {"en": "The train is very slow today.", "vi": "Hôm nay tàu đi rất chậm."}, {"en": "Let's wait for the next bus.", "vi": "Hãy đợi chuyến xe buýt tiếp theo."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ a taxi.", "answer": "took", "hint": "đã đi/bắt (taxi)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "The bus _____.", "answer": "arrived", "hint": "đã đến"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "We _____ to Japan.", "answer": "flew", "hint": "đã bay (quá khứ của fly)"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I missed the _____.", "answer": "bus", "hint": "xe buýt"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Train _____.", "answer": "station", "hint": "nhà ga"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Go by _____.", "answer": "train", "hint": "tàu hỏa"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Ride a _____.", "answer": "bicycle", "hint": "xe đạp"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "At the _____.", "answer": "airport", "hint": "sân bay"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Drive a _____.", "answer": "car", "hint": "ô tô"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Ride a _____.", "answer": "motorbike", "hint": "xe máy"}],
        "quizzes": [{"question": "'Plane' nghĩa là gì?", "options": ["Ô tô", "Máy bay", "Tàu thủy", "Xe đạp"], "correct": 1}, {"question": "I _____ to work by bus yesterday.", "options": ["go", "went", "goes", "going"], "correct": 1}, {"question": "She _____ not drive.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "Did you _____ the train?", "options": ["miss", "missed", "misses", "missing"], "correct": 0}, {"question": "The bus _____ late.", "options": ["is", "was", "were", "did"], "correct": 1}, {"question": "We _____ by ship.", "options": ["travel", "traveled", "travels", "traveling"], "correct": 1}, {"question": "'Station' nghĩa là gì?", "options": ["Nhà ga", "Sân bay", "Bến cảng", "Đường đi"], "correct": 0}, {"question": "I _____ not take a taxi.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "He _____ his bicycle.", "options": ["ride", "rode", "rides", "riding"], "correct": 1}, {"question": "The plane _____ safely.", "options": ["land", "landed", "lands", "landing"], "correct": 1}]
    },
    21: { # Emotions
        "grammar_affirmative": [{"en": "I felt very happy.", "vi": "Tôi đã cảm thấy rất hạnh phúc."}, {"en": "She cried after the movie.", "vi": "Cô ấy đã khóc sau bộ phim."}, {"en": "They smiled at me.", "vi": "Họ đã mỉm cười với tôi."}],
        "grammar_negative": [{"en": "I didn't feel angry.", "vi": "Tôi đã không cảm thấy tức giận."}, {"en": "He wasn't sad.", "vi": "Anh ấy đã không buồn."}, {"en": "We didn't laugh.", "vi": "Chúng tôi đã không cười."}],
        "vocabulary": [
            {"word": "Emotion", "phonetic": "/ɪˈmoʊ.ʃən/", "meaning": "Cảm xúc", "example": "Strong emotions.", "exampleVi": "Cảm xúc mạnh mẽ."},
            {"word": "Happy", "phonetic": "/ˈhæp.i/", "meaning": "Hạnh phúc", "example": "I am happy.", "exampleVi": "Tôi hạnh phúc."},
            {"word": "Sad", "phonetic": "/sæd/", "meaning": "Buồn", "example": "Don't be sad.", "exampleVi": "Đừng buồn."},
            {"word": "Angry", "phonetic": "/ˈæŋ.ɡri/", "meaning": "Tức giận", "example": "He is angry.", "exampleVi": "Anh ấy đang tức giận."},
            {"word": "Surprised", "phonetic": "/sɚˈpraɪzd/", "meaning": "Ngạc nhiên", "example": "A surprised look.", "exampleVi": "Một vẻ mặt ngạc nhiên."},
            {"word": "Scared", "phonetic": "/skerd/", "meaning": "Sợ hãi", "example": "I am scared.", "exampleVi": "Tôi sợ hãi."},
            {"word": "Excited", "phonetic": "/ɪkˈsaɪ.t̬ɪd/", "meaning": "Hào hứng", "example": "Very excited.", "exampleVi": "Rất hào hứng."},
            {"word": "Bored", "phonetic": "/bɔːrd/", "meaning": "Chán nản", "example": "I feel bored.", "exampleVi": "Tôi thấy chán."},
            {"word": "Smile", "phonetic": "/smaɪl/", "meaning": "Mỉm cười", "example": "A big smile.", "exampleVi": "Một nụ cười lớn."},
            {"word": "Laugh", "phonetic": "/læf/", "meaning": "Cười to", "example": "Don't laugh.", "exampleVi": "Đừng cười."}
        ],
        "listening": [{"en": "I felt very happy when I saw her.", "vi": "Tôi đã cảm thấy rất hạnh phúc khi gặp cô ấy."}, {"en": "She was sad because she lost her key.", "vi": "Cô ấy đã buồn vì đánh mất chìa khóa."}, {"en": "He got angry at the broken computer.", "vi": "Anh ấy đã tức giận vì cái máy tính bị hỏng."}, {"en": "We were surprised by the news.", "vi": "Chúng tôi đã ngạc nhiên trước tin tức đó."}, {"en": "I was scared of the big dog.", "vi": "Tôi đã sợ con chó lớn đó."}, {"en": "They were excited about the trip.", "vi": "Họ đã rất hào hứng về chuyến đi."}, {"en": "I felt a bit bored during the meeting.", "vi": "Tôi cảm thấy hơi chán trong cuộc họp."}, {"en": "She smiled at everyone in the room.", "vi": "Cô ấy đã mỉm cười với mọi người trong phòng."}, {"en": "We laughed at the funny joke.", "vi": "Chúng tôi đã cười vì câu đùa hài hước."}, {"en": "Did you feel better after the talk?", "vi": "Bạn có cảm thấy tốt hơn sau cuộc trò chuyện không?"}],
        "speaking": [{"en": "How did you feel yesterday?", "vi": "Hôm qua bạn cảm thấy thế nào?"}, {"en": "I felt very happy.", "vi": "Tôi đã cảm thấy rất hạnh phúc."}, {"en": "Why?", "vi": "Tại sao?"}, {"en": "Because I passed the exam.", "vi": "Vì tôi đã vượt qua kỳ thi."}, {"en": "Was he angry?", "vi": "Anh ấy có tức giận không?"}, {"en": "No, he was just surprised.", "vi": "Không, anh ấy chỉ ngạc nhiên thôi."}, {"en": "Don't be scared.", "vi": "Đừng sợ."}, {"en": "I am excited for tomorrow.", "vi": "Tôi hào hứng cho ngày mai."}, {"en": "She has a beautiful smile.", "vi": "Cô ấy có nụ cười đẹp."}, {"en": "We laughed a lot.", "vi": "Chúng tôi đã cười rất nhiều."}],
        "writing": [{"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I _____ very happy.", "answer": "felt", "hint": "đã cảm thấy"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "She _____ after the movie.", "answer": "cried", "hint": "đã khóc"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "They _____ at me.", "answer": "smiled", "hint": "đã mỉm cười"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "He was _____.", "answer": "angry", "hint": "tức giận"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I was _____.", "answer": "scared", "hint": "sợ hãi"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "We _____ a lot.", "answer": "laughed", "hint": "đã cười"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Don't be _____.", "answer": "sad", "hint": "buồn"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "Very _____.", "answer": "excited", "hint": "hào hứng"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "I feel _____.", "answer": "bored", "hint": "chán"}, {"type": "fill-blank", "instruction": "Điền vào chỗ trống", "question": "A big _____.", "answer": "smile", "hint": "nụ cười"}],
        "quizzes": [{"question": "'Happy' nghĩa là gì?", "options": ["Buồn", "Giận", "Hạnh phúc", "Sợ"], "correct": 2}, {"question": "I _____ happy yesterday.", "options": ["was", "were", "am", "did"], "correct": 0}, {"question": "She _____ not cry.", "options": ["did", "does", "was", "is"], "correct": 0}, {"question": "They _____ surprised.", "options": ["was", "were", "is", "are"], "correct": 1}, {"question": "He _____ angry at me.", "options": ["get", "got", "gets", "getting"], "correct": 1}, {"question": "I _____ feel scared.", "options": ["didn't", "don't", "wasn't", "not"], "correct": 0}, {"question": "'Angry' nghĩa là gì?", "options": ["Vui", "Buồn", "Giận", "Lo"], "correct": 2}, {"question": "We _____ a lot.", "options": ["laugh", "laughed", "laughs", "laughing"], "correct": 1}, {"question": "A beautiful _____.", "options": ["smile", "smiled", "smiles", "smiling"], "correct": 0}, {"question": "Was she _____?", "options": ["sad", "sadly", "sadder", "saddest"], "correct": 0}]
    }
}

for d in week3_data:
    update_lesson(d, week3_data[d])
print("Week 3 Batch 2 updated.")
